"""Embedded reason-code -> schema registry snapshot.

This baseline allows strict schema validation in PY-only deployments where
governance assets may not be mounted as sibling files.
"""

from __future__ import annotations

from typing import Final


EMBEDDED_REASON_CODE_TO_SCHEMA_REF: Final[dict[str, str]] = {
    # Kernel BLOCKED codes
    "BLOCKED-BOOTSTRAP-NOT-SATISFIED": "governance/assets/schemas/reason_payload_blocked_core.v1.json",
    "BLOCKED-START-REQUIRED": "governance/assets/schemas/reason_payload_blocked_core.v1.json",
    "BLOCKED-MISSING-CORE-RULES": "governance/assets/schemas/reason_payload_blocked_core.v1.json",
    "BLOCKED-RULEBOOK-LOAD-FAILED": "governance/assets/schemas/reason_payload_blocked_core.v1.json",
    "BLOCKED-MISSING-PROFILE": "governance/assets/schemas/reason_payload_blocked_core.v1.json",
    "BLOCKED-AMBIGUOUS-PROFILE": "governance/assets/schemas/reason_payload_blocked_core.v1.json",
    "BLOCKED-MISSING-DECISION": "governance/assets/schemas/reason_payload_blocked_core.v1.json",
    "BLOCKED-MISSING-TEMPLATES": "governance/assets/schemas/reason_payload_blocked_core.v1.json",
    "BLOCKED-MISSING-RULEBOOK": "governance/assets/schemas/reason_payload_blocked_core.v1.json",
    "BLOCKED-MISSING-ADDON": "governance/assets/schemas/reason_payload_blocked_core.v1.json",
    "BLOCKED-ADDON-CONFLICT": "governance/assets/schemas/reason_payload_blocked_core.v1.json",
    "BLOCKED-ACTIVATION-DELTA-MISMATCH": "governance/assets/schemas/reason_payload_blocked_core.v1.json",
    "BLOCKED-RULEBOOK-EVIDENCE-MISSING": "governance/assets/schemas/reason_payload_blocked_core.v1.json",
    "BLOCKED-WORKSPACE-MEMORY-INVALID": "governance/assets/schemas/reason_payload_blocked_core.v1.json",
    "BLOCKED-MISSING-EVIDENCE": "governance/assets/schemas/reason_payload_blocked_core.v1.json",
    "BLOCKED-RESUME-STATE-VIOLATION": "governance/assets/schemas/reason_payload_blocked_core.v1.json",
    "BLOCKED-MISSING-BINDING-FILE": "governance/assets/schemas/reason_payload_blocked_core.v1.json",
    "BLOCKED-MISSING-COMMANDS-HOME": "governance/assets/schemas/reason_payload_blocked_core.v1.json",
    "BLOCKED-VARIABLE-RESOLUTION": "governance/assets/schemas/reason_payload_blocked_core.v1.json",
    "BLOCKED-WORKSPACE-PERSISTENCE": "governance/assets/schemas/reason_payload_blocked_core.v1.json",
    "BLOCKED-ENGINE-SELFCHECK": "governance/assets/schemas/reason_payload_blocked_core.v1.json",
    "BLOCKED-REPO-IDENTITY-RESOLUTION": "governance/assets/schemas/reason_payload_blocked_core.v1.json",
    "BLOCKED-SYSTEM-MODE-REQUIRED": "governance/assets/schemas/reason_payload_blocked_core.v1.json",
    "BLOCKED-OPERATING-MODE-REQUIRED": "governance/assets/schemas/reason_payload_blocked_core.v1.json",
    "BLOCKED-STATE-OUTDATED": "governance/assets/schemas/reason_payload_blocked_core.v1.json",
    "BLOCKED-PACK-LOCK-REQUIRED": "governance/assets/schemas/reason_payload_blocked_core.v1.json",
    "BLOCKED-PACK-LOCK-INVALID": "governance/assets/schemas/reason_payload_blocked_core.v1.json",
    "BLOCKED-PACK-LOCK-MISMATCH": "governance/assets/schemas/reason_payload_blocked_core.v1.json",
    "BLOCKED-SURFACE-CONFLICT": "governance/assets/schemas/reason_payload_blocked_core.v1.json",
    "BLOCKED-RULESET-HASH-MISMATCH": "governance/assets/schemas/reason_payload_blocked_core.v1.json",
    "BLOCKED-ACTIVATION-HASH-MISMATCH": "governance/assets/schemas/reason_payload_blocked_core.v1.json",
    "BLOCKED-RELEASE-HYGIENE": "governance/assets/schemas/reason_payload_blocked_core.v1.json",
    "BLOCKED-SESSION-STATE-LEGACY-UNSUPPORTED": "governance/assets/schemas/reason_payload_blocked_core.v1.json",
    "BLOCKED-UNSPECIFIED": "governance/assets/schemas/reason_payload_blocked_core.v1.json",
    "BLOCKED-PERSISTENCE-TARGET-DEGENERATE": "governance/assets/schemas/reason_payload_blocked_core.v1.json",
    "BLOCKED-PERSISTENCE-PATH-VIOLATION": "governance/assets/schemas/reason_payload_blocked_core.v1.json",
    "BLOCKED-PERMISSION-DENIED": "governance/assets/schemas/reason_payload_blocked_core.v1.json",
    "BLOCKED-EXEC-DISALLOWED": "governance/assets/schemas/reason_payload_blocked_core.v1.json",
    "BLOCKED-FINGERPRINT-MISMATCH": "governance/assets/schemas/reason_payload_blocked_core.v1.json",
    "BLOCKED-INTEGRITY-FAILED": "governance/assets/schemas/reason_payload_blocked_core.v1.json",
    "BLOCKED-REPO-ROOT-NOT-DETECTABLE": "governance/assets/schemas/reason_payload_blocked_core.v1.json",
    "BLOCKED-LEGACY-DECISION-PACK-FORMAT": "governance/assets/schemas/reason_payload_blocked_core.v1.json",
    "BLOCKED-INVALID-NEXT-ACTION": "governance/assets/schemas/reason_payload_blocked_core.v1.json",
    "BLOCKED-GOLDEN-BASELINE-MODIFIED-IN-PR": "governance/assets/schemas/reason_payload_blocked_core.v1.json",
    "BLOCKED-2-REPO-DISCOVERY": "governance/assets/schemas/reason_payload_blocked_core.v1.json",
    "BLOCKED-R": "governance/assets/schemas/reason_payload_blocked_core.v1.json",
    "BLOCKED-P5-3-TEST-QUALITY-GATE": "governance/assets/schemas/reason_payload_blocked_core.v1.json",
    "BLOCKED-P5-4-BUSINESS-RULES-GATE": "governance/assets/schemas/reason_payload_blocked_core.v1.json",
    "BLOCKED-P5-6-ROLLBACK-SAFETY-GATE": "governance/assets/schemas/reason_payload_blocked_core.v1.json",
    "BLOCKED-P5-5-TECHNICAL-DEBT-GATE": "governance/assets/schemas/reason_payload_blocked_core.v1.json",
    "BLOCKED-REVIEW-DECISION-INVALID": "governance/assets/schemas/reason_payload_blocked_core.v1.json",
    "BLOCKED-P4-INTAKE-MISSING-EVIDENCE": "governance/assets/schemas/reason_payload_blocked_core.v1.json",
    "BLOCKED-P5-PLAN-RECORD-PERSIST": "governance/assets/schemas/reason_payload_blocked_core.v1.json",
    "BLOCKED-P5-PHASE-MISMATCH": "governance/assets/schemas/reason_payload_blocked_core.v1.json",
    "BLOCKED-P5-TICKET-EVIDENCE-MISSING": "governance/assets/schemas/reason_payload_blocked_core.v1.json",
    "BLOCKED-P5-PLAN-EMPTY": "governance/assets/schemas/reason_payload_blocked_core.v1.json",
    "BLOCKED-P5-REVIEW-PERSIST-FAILED": "governance/assets/schemas/reason_payload_blocked_core.v1.json",
    "BLOCKED-P6-PREREQUISITES-NOT-MET": "governance/assets/schemas/reason_payload_blocked_core.v1.json",
    "BLOCKED-P6-PLAN-COMPLIANCE-MAJOR": "governance/assets/schemas/reason_payload_blocked_core.v1.json",
    "BLOCKED-PIPELINE-INTERACTIVE": "governance/assets/schemas/reason_payload_blocked_core.v1.json",
    "BLOCKED-PIPELINE-HUMAN-ASSIST": "governance/assets/schemas/reason_payload_blocked_core.v1.json",
    "BLOCKED-PIPELINE-PROMPT-BUDGET": "governance/assets/schemas/reason_payload_blocked_core.v1.json",
    "BLOCKED-RECEIPT-MISSING-TYPE": "governance/assets/schemas/reason_payload_blocked_core.v1.json",
    "BLOCKED-RECEIPT-MISSING-GATE": "governance/assets/schemas/reason_payload_blocked_core.v1.json",
    "BLOCKED-RECEIPT-MISSING-DIGEST": "governance/assets/schemas/reason_payload_blocked_core.v1.json",
    "BLOCKED-RECEIPT-MISSING-SESSION": "governance/assets/schemas/reason_payload_blocked_core.v1.json",
    "BLOCKED-RECEIPT-MISSING-STATE-REVISION": "governance/assets/schemas/reason_payload_blocked_core.v1.json",
    "BLOCKED-RECEIPT-MISSING-SCOPE": "governance/assets/schemas/reason_payload_blocked_core.v1.json",
    "BLOCKED-RECEIPT-MISSING-TIMESTAMP": "governance/assets/schemas/reason_payload_blocked_core.v1.json",
    "BLOCKED-RECEIPT-TYPE-MISMATCH": "governance/assets/schemas/reason_payload_blocked_core.v1.json",
    "BLOCKED-RECEIPT-GATE-MISMATCH": "governance/assets/schemas/reason_payload_blocked_core.v1.json",
    "BLOCKED-RECEIPT-DIGEST-MISMATCH": "governance/assets/schemas/reason_payload_blocked_core.v1.json",
    "BLOCKED-RECEIPT-SESSION-MISMATCH": "governance/assets/schemas/reason_payload_blocked_core.v1.json",
    "BLOCKED-RECEIPT-STATE-REVISION-MISMATCH": "governance/assets/schemas/reason_payload_blocked_core.v1.json",
    "BLOCKED-RECEIPT-SCOPE-MISMATCH": "governance/assets/schemas/reason_payload_blocked_core.v1.json",
    "BLOCKED-RECEIPT-INVALID-TIMESTAMP": "governance/assets/schemas/reason_payload_blocked_core.v1.json",
    "BLOCKED-RECEIPT-STALE-TIMESTAMP": "governance/assets/schemas/reason_payload_blocked_core.v1.json",
    # Strict-exit enforcement
    "BLOCKED-STRICT-EVIDENCE-MISSING": "governance/assets/schemas/strict_exit_blocked.v1.schema.json",
    "BLOCKED-STRICT-EVIDENCE-STALE": "governance/assets/schemas/strict_exit_blocked.v1.schema.json",
    "BLOCKED-STRICT-THRESHOLD": "governance/assets/schemas/strict_exit_blocked.v1.schema.json",
    "BLOCKED-STRICT-CONTRACT-MISSING": "governance/assets/schemas/strict_exit_blocked.v1.schema.json",
    "NOT_VERIFIED-STRICT-EVIDENCE-STALE": "governance/assets/schemas/reason_payload_advisory.v1.json",
    "NOT_VERIFIED-STRICT-EVIDENCE-MISSING": "governance/assets/schemas/reason_payload_advisory.v1.json",
    # Install subsystem
    "BLOCKED-INSTALL-PRECHECK-MISSING-SOURCE": "governance/assets/schemas/reason_payload_blocked_core.v1.json",
    "BLOCKED-INSTALL-VERSION-MISSING": "governance/assets/schemas/reason_payload_blocked_core.v1.json",
    "BLOCKED-INSTALL-CONFIG-ROOT-INVALID": "governance/assets/schemas/reason_payload_blocked_core.v1.json",
    # Contract drift
    "BLOCKED-CONTRACT-LAYOUT-DRIFT": "governance/assets/schemas/reason_payload_blocked_core.v1.json",
    "BLOCKED-CONTRACT-RUNTIME-DRIFT": "governance/assets/schemas/reason_payload_blocked_core.v1.json",
    "BLOCKED-CONTRACT-OPENCODE-DRIFT": "governance/assets/schemas/reason_payload_blocked_core.v1.json",
    # Model identity
    "BLOCKED-MODEL-IDENTITY-UNTRUSTED": "governance/assets/schemas/reason_payload_blocked_core.v1.json",
    "BLOCKED-MODEL-CONTEXT-LIMIT-REQUIRED": "governance/assets/schemas/reason_payload_blocked_core.v1.json",
    "BLOCKED-MODEL-CONTEXT-LIMIT-UNKNOWN": "governance/assets/schemas/reason_payload_blocked_core.v1.json",
    "BLOCKED-MODEL-CONTEXT-LIMIT-INVALID": "governance/assets/schemas/reason_payload_blocked_core.v1.json",
    "BLOCKED-MODEL-METADATA-FETCH-FAILED": "governance/assets/schemas/reason_payload_blocked_core.v1.json",
    "BLOCKED-MODEL-IDENTITY-SOURCE-INVALID": "governance/assets/schemas/reason_payload_blocked_core.v1.json",
    # Profile/addon BLOCKED codes
    "BLOCKED-MISSING-DB-VERSION": "governance/assets/schemas/reason_payload_blocked_core.v1.json",
    "BLOCKED-FORMAT-UNDEFINED": "governance/assets/schemas/reason_payload_blocked_core.v1.json",
    "BLOCKED-MIGRATION-UNSAFE": "governance/assets/schemas/reason_payload_blocked_core.v1.json",
    "BLOCKED-MIGRATION-NO-ROLLBACK": "governance/assets/schemas/reason_payload_blocked_core.v1.json",
    "BLOCKED-MIGRATION-COMPATIBILITY": "governance/assets/schemas/reason_payload_blocked_core.v1.json",
    # Operational
    "REPO-DOC-UNSAFE-DIRECTIVE": "governance/assets/schemas/reason_payload_repo_doc_unsafe.v1.json",
    "REPO-CONSTRAINT-WIDENING": "governance/assets/schemas/reason_payload_repo_constraint_widening.v1.json",
    "INTERACTIVE-REQUIRED-IN-PIPELINE": "governance/assets/schemas/reason_payload_interactive_pipeline.v1.json",
    "PROMPT-BUDGET-EXCEEDED": "governance/assets/schemas/reason_payload_prompt_budget.v1.json",
    # Persistence gate
    "PERSIST_CONFIRMATION_REQUIRED": "governance/assets/schemas/reason_payload_blocked_core.v1.json",
    "PERSIST_CONFIRMATION_INVALID": "governance/assets/schemas/reason_payload_blocked_core.v1.json",
    "PERSIST_DISALLOWED_IN_PIPELINE": "governance/assets/schemas/reason_payload_blocked_core.v1.json",
    "PERSIST_PHASE_MISMATCH": "governance/assets/schemas/reason_payload_blocked_core.v1.json",
    "PERSIST_GATE_NOT_APPROVED": "governance/assets/schemas/reason_payload_blocked_core.v1.json",
    # WARN
    "WARN-UNMAPPED-AUDIT-REASON": "governance/assets/schemas/reason_payload_advisory.v1.json",
    "WARN-WORKSPACE-PERSISTENCE": "governance/assets/schemas/reason_payload_advisory.v1.json",
    "WARN-ENGINE-LIVE-DENIED": "governance/assets/schemas/reason_payload_advisory.v1.json",
    "WARN-MODE-DOWNGRADED": "governance/assets/schemas/reason_payload_advisory.v1.json",
    "WARN-PERMISSION-LIMITED": "governance/assets/schemas/reason_payload_advisory.v1.json",
    "WARN-SESSION-STATE-LEGACY-COMPAT-MODE": "governance/assets/schemas/reason_payload_advisory.v1.json",
    # NOT_VERIFIED
    "NOT_VERIFIED-MISSING-EVIDENCE": "governance/assets/schemas/reason_payload_advisory.v1.json",
    "NOT_VERIFIED-EVIDENCE-STALE": "governance/assets/schemas/reason_payload_advisory.v1.json",
    # WARN — profile/addon
    "WARN-DOCS-README-DRIFT": "governance/assets/schemas/reason_payload_advisory.v1.json",
    "WARN-DOCS-SCHEMA-DRIFT": "governance/assets/schemas/reason_payload_advisory.v1.json",
    "WARN-DOCS-MANIFEST-RULEBOOK-MISSING": "governance/assets/schemas/reason_payload_advisory.v1.json",
    "WARN-FALLBACK-BASELINE-UNKNOWN": "governance/assets/schemas/reason_payload_advisory.v1.json",
    "WARN-FALLBACK-TESTING-INSUFFICIENT": "governance/assets/schemas/reason_payload_advisory.v1.json",
    "WARN-FALLBACK-RECOVERY-UNSPECIFIED": "governance/assets/schemas/reason_payload_advisory.v1.json",
    "WARN-PRINCIPAL-EVIDENCE-MISSING": "governance/assets/schemas/reason_payload_advisory.v1.json",
    "WARN-SCORECARD-CALIBRATION-INCOMPLETE": "governance/assets/schemas/reason_payload_advisory.v1.json",
    "WARN-RISK-TIER-UNRESOLVED": "governance/assets/schemas/reason_payload_advisory.v1.json",
    "WARN-OPENAPI-SPEC-IMPLEMENTATION-MISMATCH": "governance/assets/schemas/reason_payload_advisory.v1.json",
    "WARN-OPENAPI-VERSION-UNKNOWN": "governance/assets/schemas/reason_payload_advisory.v1.json",
    "WARN-OPENAPI-MISSING-SPEC": "governance/assets/schemas/reason_payload_advisory.v1.json",
    "WARN-OPENAPI-BREAKING-CHANGE-UNAPPROVED": "governance/assets/schemas/reason_payload_advisory.v1.json",
    "WARN-FE-OPENAPI-GENERATOR-UNKNOWN": "governance/assets/schemas/reason_payload_advisory.v1.json",
    "WARN-FE-OPENAPI-DRIFT-RISK": "governance/assets/schemas/reason_payload_advisory.v1.json",
    "WARN-FE-OPENAPI-NO-NEGATIVE-TEST": "governance/assets/schemas/reason_payload_advisory.v1.json",
    "WARN-FE-OPENAPI-SOURCE-UNRESOLVED": "governance/assets/schemas/reason_payload_advisory.v1.json",
    "WARN-FE-OPENAPI-MAPPING-DRIFT-RISK": "governance/assets/schemas/reason_payload_advisory.v1.json",
    "WARN-FE-OPENAPI-CONTRACT-TEST-MISSING": "governance/assets/schemas/reason_payload_advisory.v1.json",
    "WARN-KAFKA-IDEMPOTENCY-UNVERIFIED": "governance/assets/schemas/reason_payload_advisory.v1.json",
    "WARN-KAFKA-RETRY-POLICY-UNKNOWN": "governance/assets/schemas/reason_payload_advisory.v1.json",
    "WARN-KAFKA-ASYNC-FLAKINESS-RISK": "governance/assets/schemas/reason_payload_advisory.v1.json",
    "WARN-CYPRESS-FLAKY-RISK": "governance/assets/schemas/reason_payload_advisory.v1.json",
    "WARN-CYPRESS-SELECTOR-UNSTABLE": "governance/assets/schemas/reason_payload_advisory.v1.json",
    "WARN-CYPRESS-NO-CRITICAL-FLOW-COVERAGE": "governance/assets/schemas/reason_payload_advisory.v1.json",
    "WARN-CYPRESS-NETWORK-CONTROL-MISSING": "governance/assets/schemas/reason_payload_advisory.v1.json",
    "WARN-CYPRESS-CRITICAL-PATH-MISSING": "governance/assets/schemas/reason_payload_advisory.v1.json",
    "WARN-CYPRESS-ASYNC-FLAKE-RISK": "governance/assets/schemas/reason_payload_advisory.v1.json",
    "WARN-CUCUMBER-VERSION-UNKNOWN": "governance/assets/schemas/reason_payload_advisory.v1.json",
    "WARN-CUCUMBER-RUNNER-UNKNOWN": "governance/assets/schemas/reason_payload_advisory.v1.json",
    "WARN-CUCUMBER-CONVENTIONS-UNKNOWN": "governance/assets/schemas/reason_payload_advisory.v1.json",
    "WARN-CUCUMBER-FLAKINESS-RISK": "governance/assets/schemas/reason_payload_advisory.v1.json",
    "WARN-CUCUMBER-NO-EVIDENCE": "governance/assets/schemas/reason_payload_advisory.v1.json",
    "WARN-JAVA-DETERMINISM-RISK": "governance/assets/schemas/reason_payload_advisory.v1.json",
    "WARN-BUILD-TOOL-MISSING": "governance/assets/schemas/reason_payload_advisory.v1.json",
    "WARN-ANGULAR-BOUNDARY-DRIFT": "governance/assets/schemas/reason_payload_advisory.v1.json",
    "WARN-ANGULAR-STATE-PATTERN-MIX": "governance/assets/schemas/reason_payload_advisory.v1.json",
    "WARN-ANGULAR-ASYNC-DETERMINISM": "governance/assets/schemas/reason_payload_advisory.v1.json",
    "WARN-PYTHON-MIGRATION-ROLLBACK-MISSING": "governance/assets/schemas/reason_payload_advisory.v1.json",
    "WARN-PYTHON-ASYNC-DETERMINISM": "governance/assets/schemas/reason_payload_advisory.v1.json",
    "WARN-PYTHON-TYPE-CHECK-SKIPPED": "governance/assets/schemas/reason_payload_advisory.v1.json",
    "WARN-LIQUIBASE-PG-VERSION-UNKNOWN": "governance/assets/schemas/reason_payload_advisory.v1.json",
    "WARN-LIQUIBASE-ROLLBACK-MISSING": "governance/assets/schemas/reason_payload_advisory.v1.json",
    "WARN-LIQUIBASE-LOCK-RISK": "governance/assets/schemas/reason_payload_advisory.v1.json",
    "WARN-LIQUIBASE-DATA-MIGRATION-UNVERIFIED": "governance/assets/schemas/reason_payload_advisory.v1.json",
    "WARN-SESSION-STATE-SCHEMA-VIOLATION": "governance/assets/schemas/reason_payload_advisory.v1.json",
    "WARN-P6-PLAN-COMPLIANCE-DRIFT": "governance/assets/schemas/reason_payload_advisory.v1.json",
    "WARN-P6-STATE-INCONSISTENCY": "governance/assets/schemas/reason_payload_advisory.v1.json",
    # Audit events
    "REPO-CONSTRAINT-UNSUPPORTED": "governance/assets/schemas/reason_payload_repo_constraint_unsupported.v1.json",
    "POLICY-PRECEDENCE-APPLIED": "governance/assets/schemas/reason_payload_policy_precedence.v1.json",
}
