"""Embedded reason-code -> schema registry snapshot.

This baseline allows strict schema validation in PY-only deployments where
diagnostics assets may not be mounted as sibling files.
"""

from __future__ import annotations

from typing import Final


EMBEDDED_REASON_CODE_TO_SCHEMA_REF: Final[dict[str, str]] = {
    # Kernel BLOCKED codes
    "BLOCKED-BOOTSTRAP-NOT-SATISFIED": "diagnostics/schemas/reason_payload_blocked_core.v1.json",
    "BLOCKED-START-REQUIRED": "diagnostics/schemas/reason_payload_blocked_core.v1.json",
    "BLOCKED-MISSING-CORE-RULES": "diagnostics/schemas/reason_payload_blocked_core.v1.json",
    "BLOCKED-RULEBOOK-LOAD-FAILED": "diagnostics/schemas/reason_payload_blocked_core.v1.json",
    "BLOCKED-MISSING-PROFILE": "diagnostics/schemas/reason_payload_blocked_core.v1.json",
    "BLOCKED-AMBIGUOUS-PROFILE": "diagnostics/schemas/reason_payload_blocked_core.v1.json",
    "BLOCKED-MISSING-DECISION": "diagnostics/schemas/reason_payload_blocked_core.v1.json",
    "BLOCKED-MISSING-TEMPLATES": "diagnostics/schemas/reason_payload_blocked_core.v1.json",
    "BLOCKED-MISSING-RULEBOOK": "diagnostics/schemas/reason_payload_blocked_core.v1.json",
    "BLOCKED-MISSING-ADDON": "diagnostics/schemas/reason_payload_blocked_core.v1.json",
    "BLOCKED-ADDON-CONFLICT": "diagnostics/schemas/reason_payload_blocked_core.v1.json",
    "BLOCKED-ACTIVATION-DELTA-MISMATCH": "diagnostics/schemas/reason_payload_blocked_core.v1.json",
    "BLOCKED-RULEBOOK-EVIDENCE-MISSING": "diagnostics/schemas/reason_payload_blocked_core.v1.json",
    "BLOCKED-WORKSPACE-MEMORY-INVALID": "diagnostics/schemas/reason_payload_blocked_core.v1.json",
    "BLOCKED-MISSING-EVIDENCE": "diagnostics/schemas/reason_payload_blocked_core.v1.json",
    "BLOCKED-RESUME-STATE-VIOLATION": "diagnostics/schemas/reason_payload_blocked_core.v1.json",
    "BLOCKED-MISSING-BINDING-FILE": "diagnostics/schemas/reason_payload_blocked_core.v1.json",
    "BLOCKED-VARIABLE-RESOLUTION": "diagnostics/schemas/reason_payload_blocked_core.v1.json",
    "BLOCKED-WORKSPACE-PERSISTENCE": "diagnostics/schemas/reason_payload_blocked_core.v1.json",
    "BLOCKED-ENGINE-SELFCHECK": "diagnostics/schemas/reason_payload_blocked_core.v1.json",
    "BLOCKED-REPO-IDENTITY-RESOLUTION": "diagnostics/schemas/reason_payload_blocked_core.v1.json",
    "BLOCKED-SYSTEM-MODE-REQUIRED": "diagnostics/schemas/reason_payload_blocked_core.v1.json",
    "BLOCKED-OPERATING-MODE-REQUIRED": "diagnostics/schemas/reason_payload_blocked_core.v1.json",
    "BLOCKED-STATE-OUTDATED": "diagnostics/schemas/reason_payload_blocked_core.v1.json",
    "BLOCKED-PACK-LOCK-REQUIRED": "diagnostics/schemas/reason_payload_blocked_core.v1.json",
    "BLOCKED-PACK-LOCK-INVALID": "diagnostics/schemas/reason_payload_blocked_core.v1.json",
    "BLOCKED-PACK-LOCK-MISMATCH": "diagnostics/schemas/reason_payload_blocked_core.v1.json",
    "BLOCKED-SURFACE-CONFLICT": "diagnostics/schemas/reason_payload_blocked_core.v1.json",
    "BLOCKED-RULESET-HASH-MISMATCH": "diagnostics/schemas/reason_payload_blocked_core.v1.json",
    "BLOCKED-ACTIVATION-HASH-MISMATCH": "diagnostics/schemas/reason_payload_blocked_core.v1.json",
    "BLOCKED-RELEASE-HYGIENE": "diagnostics/schemas/reason_payload_blocked_core.v1.json",
    "BLOCKED-SESSION-STATE-LEGACY-UNSUPPORTED": "diagnostics/schemas/reason_payload_blocked_core.v1.json",
    "BLOCKED-UNSPECIFIED": "diagnostics/schemas/reason_payload_blocked_core.v1.json",
    "BLOCKED-PERSISTENCE-TARGET-DEGENERATE": "diagnostics/schemas/reason_payload_blocked_core.v1.json",
    "BLOCKED-PERSISTENCE-PATH-VIOLATION": "diagnostics/schemas/reason_payload_blocked_core.v1.json",
    "BLOCKED-PERMISSION-DENIED": "diagnostics/schemas/reason_payload_blocked_core.v1.json",
    "BLOCKED-EXEC-DISALLOWED": "diagnostics/schemas/reason_payload_blocked_core.v1.json",
    "BLOCKED-FINGERPRINT-MISMATCH": "diagnostics/schemas/reason_payload_blocked_core.v1.json",
    "BLOCKED-GOLDEN-BASELINE-MODIFIED-IN-PR": "diagnostics/schemas/reason_payload_blocked_core.v1.json",
    "BLOCKED-Phase2-RepoDiscovery": "diagnostics/schemas/reason_payload_blocked_core.v1.json",
    "BLOCKED-R": "diagnostics/schemas/reason_payload_blocked_core.v1.json",
    "BLOCKED-P5-3-TEST-QUALITY-GATE": "diagnostics/schemas/reason_payload_blocked_core.v1.json",
    "BLOCKED-P5-4-BUSINESS-RULES-GATE": "diagnostics/schemas/reason_payload_blocked_core.v1.json",
    "BLOCKED-P5-6-ROLLBACK-SAFETY-GATE": "diagnostics/schemas/reason_payload_blocked_core.v1.json",
    "BLOCKED-P6-PREREQUISITES-NOT-MET": "diagnostics/schemas/reason_payload_blocked_core.v1.json",
    "BLOCKED-PIPELINE-INTERACTIVE": "diagnostics/schemas/reason_payload_blocked_core.v1.json",
    "BLOCKED-PIPELINE-HUMAN-ASSIST": "diagnostics/schemas/reason_payload_blocked_core.v1.json",
    # Install subsystem
    "BLOCKED-INSTALL-PRECHECK-MISSING-SOURCE": "diagnostics/schemas/reason_payload_blocked_core.v1.json",
    "BLOCKED-INSTALL-VERSION-MISSING": "diagnostics/schemas/reason_payload_blocked_core.v1.json",
    "BLOCKED-INSTALL-CONFIG-ROOT-INVALID": "diagnostics/schemas/reason_payload_blocked_core.v1.json",
    # Model identity
    "BLOCKED-MODEL-IDENTITY-UNTRUSTED": "diagnostics/schemas/reason_payload_blocked_core.v1.json",
    "BLOCKED-MODEL-CONTEXT-LIMIT-REQUIRED": "diagnostics/schemas/reason_payload_blocked_core.v1.json",
    "BLOCKED-MODEL-CONTEXT-LIMIT-UNKNOWN": "diagnostics/schemas/reason_payload_blocked_core.v1.json",
    "BLOCKED-MODEL-CONTEXT-LIMIT-INVALID": "diagnostics/schemas/reason_payload_blocked_core.v1.json",
    "BLOCKED-MODEL-METADATA-FETCH-FAILED": "diagnostics/schemas/reason_payload_blocked_core.v1.json",
    "BLOCKED-MODEL-IDENTITY-SOURCE-INVALID": "diagnostics/schemas/reason_payload_blocked_core.v1.json",
    # Profile/addon BLOCKED codes
    "BLOCKED-MISSING-DB-VERSION": "diagnostics/schemas/reason_payload_blocked_core.v1.json",
    "BLOCKED-FORMAT-UNDEFINED": "diagnostics/schemas/reason_payload_blocked_core.v1.json",
    "BLOCKED-MIGRATION-UNSAFE": "diagnostics/schemas/reason_payload_blocked_core.v1.json",
    "BLOCKED-MIGRATION-NO-ROLLBACK": "diagnostics/schemas/reason_payload_blocked_core.v1.json",
    "BLOCKED-MIGRATION-COMPATIBILITY": "diagnostics/schemas/reason_payload_blocked_core.v1.json",
    # Operational
    "REPO-DOC-UNSAFE-DIRECTIVE": "diagnostics/schemas/reason_payload_repo_doc_unsafe.v1.json",
    "REPO-CONSTRAINT-WIDENING": "diagnostics/schemas/reason_payload_repo_constraint_widening.v1.json",
    "INTERACTIVE-REQUIRED-IN-PIPELINE": "diagnostics/schemas/reason_payload_interactive_pipeline.v1.json",
    "PROMPT-BUDGET-EXCEEDED": "diagnostics/schemas/reason_payload_prompt_budget.v1.json",
    # Persistence gate
    "PERSIST_CONFIRMATION_REQUIRED": "diagnostics/schemas/reason_payload_blocked_core.v1.json",
    "PERSIST_CONFIRMATION_INVALID": "diagnostics/schemas/reason_payload_blocked_core.v1.json",
    "PERSIST_DISALLOWED_IN_PIPELINE": "diagnostics/schemas/reason_payload_blocked_core.v1.json",
    "PERSIST_PHASE_MISMATCH": "diagnostics/schemas/reason_payload_blocked_core.v1.json",
    "PERSIST_GATE_NOT_APPROVED": "diagnostics/schemas/reason_payload_blocked_core.v1.json",
    # WARN
    "WARN-UNMAPPED-AUDIT-REASON": "diagnostics/schemas/reason_payload_advisory.v1.json",
    "WARN-WORKSPACE-PERSISTENCE": "diagnostics/schemas/reason_payload_advisory.v1.json",
    "WARN-ENGINE-LIVE-DENIED": "diagnostics/schemas/reason_payload_advisory.v1.json",
    "WARN-MODE-DOWNGRADED": "diagnostics/schemas/reason_payload_advisory.v1.json",
    "WARN-PERMISSION-LIMITED": "diagnostics/schemas/reason_payload_advisory.v1.json",
    "WARN-SESSION-STATE-LEGACY-COMPAT-MODE": "diagnostics/schemas/reason_payload_advisory.v1.json",
    # NOT_VERIFIED
    "NOT_VERIFIED-MISSING-EVIDENCE": "diagnostics/schemas/reason_payload_advisory.v1.json",
    "NOT_VERIFIED-EVIDENCE-STALE": "diagnostics/schemas/reason_payload_advisory.v1.json",
    # WARN — profile/addon
    "WARN-DOCS-README-DRIFT": "diagnostics/schemas/reason_payload_advisory.v1.json",
    "WARN-DOCS-SCHEMA-DRIFT": "diagnostics/schemas/reason_payload_advisory.v1.json",
    "WARN-DOCS-MANIFEST-RULEBOOK-MISSING": "diagnostics/schemas/reason_payload_advisory.v1.json",
    "WARN-FALLBACK-BASELINE-UNKNOWN": "diagnostics/schemas/reason_payload_advisory.v1.json",
    "WARN-FALLBACK-TESTING-INSUFFICIENT": "diagnostics/schemas/reason_payload_advisory.v1.json",
    "WARN-FALLBACK-RECOVERY-UNSPECIFIED": "diagnostics/schemas/reason_payload_advisory.v1.json",
    "WARN-PRINCIPAL-EVIDENCE-MISSING": "diagnostics/schemas/reason_payload_advisory.v1.json",
    "WARN-SCORECARD-CALIBRATION-INCOMPLETE": "diagnostics/schemas/reason_payload_advisory.v1.json",
    "WARN-RISK-TIER-UNRESOLVED": "diagnostics/schemas/reason_payload_advisory.v1.json",
    "WARN-OPENAPI-SPEC-IMPLEMENTATION-MISMATCH": "diagnostics/schemas/reason_payload_advisory.v1.json",
    "WARN-OPENAPI-VERSION-UNKNOWN": "diagnostics/schemas/reason_payload_advisory.v1.json",
    "WARN-OPENAPI-MISSING-SPEC": "diagnostics/schemas/reason_payload_advisory.v1.json",
    "WARN-OPENAPI-BREAKING-CHANGE-UNAPPROVED": "diagnostics/schemas/reason_payload_advisory.v1.json",
    "WARN-FE-OPENAPI-GENERATOR-UNKNOWN": "diagnostics/schemas/reason_payload_advisory.v1.json",
    "WARN-FE-OPENAPI-DRIFT-RISK": "diagnostics/schemas/reason_payload_advisory.v1.json",
    "WARN-FE-OPENAPI-NO-NEGATIVE-TEST": "diagnostics/schemas/reason_payload_advisory.v1.json",
    "WARN-FE-OPENAPI-SOURCE-UNRESOLVED": "diagnostics/schemas/reason_payload_advisory.v1.json",
    "WARN-FE-OPENAPI-MAPPING-DRIFT-RISK": "diagnostics/schemas/reason_payload_advisory.v1.json",
    "WARN-FE-OPENAPI-CONTRACT-TEST-MISSING": "diagnostics/schemas/reason_payload_advisory.v1.json",
    "WARN-KAFKA-IDEMPOTENCY-UNVERIFIED": "diagnostics/schemas/reason_payload_advisory.v1.json",
    "WARN-KAFKA-RETRY-POLICY-UNKNOWN": "diagnostics/schemas/reason_payload_advisory.v1.json",
    "WARN-KAFKA-ASYNC-FLAKINESS-RISK": "diagnostics/schemas/reason_payload_advisory.v1.json",
    "WARN-CYPRESS-FLAKY-RISK": "diagnostics/schemas/reason_payload_advisory.v1.json",
    "WARN-CYPRESS-SELECTOR-UNSTABLE": "diagnostics/schemas/reason_payload_advisory.v1.json",
    "WARN-CYPRESS-NO-CRITICAL-FLOW-COVERAGE": "diagnostics/schemas/reason_payload_advisory.v1.json",
    "WARN-CYPRESS-NETWORK-CONTROL-MISSING": "diagnostics/schemas/reason_payload_advisory.v1.json",
    "WARN-CYPRESS-CRITICAL-PATH-MISSING": "diagnostics/schemas/reason_payload_advisory.v1.json",
    "WARN-CYPRESS-ASYNC-FLAKE-RISK": "diagnostics/schemas/reason_payload_advisory.v1.json",
    "WARN-CUCUMBER-VERSION-UNKNOWN": "diagnostics/schemas/reason_payload_advisory.v1.json",
    "WARN-CUCUMBER-RUNNER-UNKNOWN": "diagnostics/schemas/reason_payload_advisory.v1.json",
    "WARN-CUCUMBER-CONVENTIONS-UNKNOWN": "diagnostics/schemas/reason_payload_advisory.v1.json",
    "WARN-CUCUMBER-FLAKINESS-RISK": "diagnostics/schemas/reason_payload_advisory.v1.json",
    "WARN-CUCUMBER-NO-EVIDENCE": "diagnostics/schemas/reason_payload_advisory.v1.json",
    "WARN-JAVA-DETERMINISM-RISK": "diagnostics/schemas/reason_payload_advisory.v1.json",
    "WARN-BUILD-TOOL-MISSING": "diagnostics/schemas/reason_payload_advisory.v1.json",
    "WARN-ANGULAR-BOUNDARY-DRIFT": "diagnostics/schemas/reason_payload_advisory.v1.json",
    "WARN-ANGULAR-STATE-PATTERN-MIX": "diagnostics/schemas/reason_payload_advisory.v1.json",
    "WARN-ANGULAR-ASYNC-DETERMINISM": "diagnostics/schemas/reason_payload_advisory.v1.json",
    "WARN-PYTHON-MIGRATION-ROLLBACK-MISSING": "diagnostics/schemas/reason_payload_advisory.v1.json",
    "WARN-PYTHON-ASYNC-DETERMINISM": "diagnostics/schemas/reason_payload_advisory.v1.json",
    "WARN-PYTHON-TYPE-CHECK-SKIPPED": "diagnostics/schemas/reason_payload_advisory.v1.json",
    "WARN-LIQUIBASE-PG-VERSION-UNKNOWN": "diagnostics/schemas/reason_payload_advisory.v1.json",
    "WARN-LIQUIBASE-ROLLBACK-MISSING": "diagnostics/schemas/reason_payload_advisory.v1.json",
    "WARN-LIQUIBASE-LOCK-RISK": "diagnostics/schemas/reason_payload_advisory.v1.json",
    "WARN-LIQUIBASE-DATA-MIGRATION-UNVERIFIED": "diagnostics/schemas/reason_payload_advisory.v1.json",
    "WARN-SESSION-STATE-SCHEMA-VIOLATION": "diagnostics/schemas/reason_payload_advisory.v1.json",
    # Audit events
    "REPO-CONSTRAINT-UNSUPPORTED": "diagnostics/schemas/reason_payload_repo_constraint_unsupported.v1.json",
    "POLICY-PRECEDENCE-APPLIED": "diagnostics/schemas/reason_payload_policy_precedence.v1.json",
}
