"""Canonical governance reason-code registry.

SSOT for all reason codes referenced in kernel MD files (master.md, rules.md,
start.md, SESSION_STATE_SCHEMA.md) and profile/addon rulebooks.

Every reason code used in any governance surface MUST have a constant here.
The ``CANONICAL_REASON_CODES`` tuple is the single authoritative membership set
used by ``is_registered_reason_code()``.

Parameterized codes (e.g. BLOCKED-MISSING-ADDON:<key>) use a prefix-match helper
``is_registered_reason_code_or_parameterized()`` for runtime validation.
"""

from __future__ import annotations

from typing import Final

# ---------------------------------------------------------------------------
# Meta
# ---------------------------------------------------------------------------
REASON_CODE_NONE: Final[str] = "none"

# ---------------------------------------------------------------------------
# Kernel BLOCKED codes (master.md / rules.md / start.md / SESSION_STATE_SCHEMA.md)
# ---------------------------------------------------------------------------
BLOCKED_BOOTSTRAP_NOT_SATISFIED: Final[str] = "BLOCKED-BOOTSTRAP-NOT-SATISFIED"
BLOCKED_START_REQUIRED: Final[str] = "BLOCKED-START-REQUIRED"
BLOCKED_MISSING_CORE_RULES: Final[str] = "BLOCKED-MISSING-CORE-RULES"
BLOCKED_MISSING_PROFILE: Final[str] = "BLOCKED-MISSING-PROFILE"
BLOCKED_AMBIGUOUS_PROFILE: Final[str] = "BLOCKED-AMBIGUOUS-PROFILE"
BLOCKED_MISSING_DECISION: Final[str] = "BLOCKED-MISSING-DECISION"
BLOCKED_MISSING_TEMPLATES: Final[str] = "BLOCKED-MISSING-TEMPLATES"
BLOCKED_MISSING_RULEBOOK: Final[str] = "BLOCKED-MISSING-RULEBOOK"
BLOCKED_MISSING_ADDON: Final[str] = "BLOCKED-MISSING-ADDON"
BLOCKED_ADDON_CONFLICT: Final[str] = "BLOCKED-ADDON-CONFLICT"
BLOCKED_ACTIVATION_DELTA_MISMATCH: Final[str] = "BLOCKED-ACTIVATION-DELTA-MISMATCH"
BLOCKED_RULEBOOK_EVIDENCE_MISSING: Final[str] = "BLOCKED-RULEBOOK-EVIDENCE-MISSING"
BLOCKED_WORKSPACE_MEMORY_INVALID: Final[str] = "BLOCKED-WORKSPACE-MEMORY-INVALID"
BLOCKED_MISSING_EVIDENCE: Final[str] = "BLOCKED-MISSING-EVIDENCE"
BLOCKED_RESUME_STATE_VIOLATION: Final[str] = "BLOCKED-RESUME-STATE-VIOLATION"
BLOCKED_MISSING_BINDING_FILE: Final[str] = "BLOCKED-MISSING-BINDING-FILE"
BLOCKED_VARIABLE_RESOLUTION: Final[str] = "BLOCKED-VARIABLE-RESOLUTION"
BLOCKED_WORKSPACE_PERSISTENCE: Final[str] = "BLOCKED-WORKSPACE-PERSISTENCE"
BLOCKED_ENGINE_SELFCHECK: Final[str] = "BLOCKED-ENGINE-SELFCHECK"
BLOCKED_REPO_IDENTITY_RESOLUTION: Final[str] = "BLOCKED-REPO-IDENTITY-RESOLUTION"
BLOCKED_SYSTEM_MODE_REQUIRED: Final[str] = "BLOCKED-SYSTEM-MODE-REQUIRED"
BLOCKED_OPERATING_MODE_REQUIRED: Final[str] = "BLOCKED-OPERATING-MODE-REQUIRED"
BLOCKED_STATE_OUTDATED: Final[str] = "BLOCKED-STATE-OUTDATED"
BLOCKED_PACK_LOCK_REQUIRED: Final[str] = "BLOCKED-PACK-LOCK-REQUIRED"
BLOCKED_PACK_LOCK_INVALID: Final[str] = "BLOCKED-PACK-LOCK-INVALID"
BLOCKED_PACK_LOCK_MISMATCH: Final[str] = "BLOCKED-PACK-LOCK-MISMATCH"
BLOCKED_SURFACE_CONFLICT: Final[str] = "BLOCKED-SURFACE-CONFLICT"
BLOCKED_RULESET_HASH_MISMATCH: Final[str] = "BLOCKED-RULESET-HASH-MISMATCH"
BLOCKED_ACTIVATION_HASH_MISMATCH: Final[str] = "BLOCKED-ACTIVATION-HASH-MISMATCH"
BLOCKED_RELEASE_HYGIENE: Final[str] = "BLOCKED-RELEASE-HYGIENE"
BLOCKED_SESSION_STATE_LEGACY_UNSUPPORTED: Final[str] = "BLOCKED-SESSION-STATE-LEGACY-UNSUPPORTED"
BLOCKED_UNSPECIFIED: Final[str] = "BLOCKED-UNSPECIFIED"
BLOCKED_PERSISTENCE_TARGET_DEGENERATE: Final[str] = "BLOCKED-PERSISTENCE-TARGET-DEGENERATE"
BLOCKED_PERSISTENCE_PATH_VIOLATION: Final[str] = "BLOCKED-PERSISTENCE-PATH-VIOLATION"
BLOCKED_PERMISSION_DENIED: Final[str] = "BLOCKED-PERMISSION-DENIED"
BLOCKED_EXEC_DISALLOWED: Final[str] = "BLOCKED-EXEC-DISALLOWED"
BLOCKED_FINGERPRINT_MISMATCH: Final[str] = "BLOCKED-FINGERPRINT-MISMATCH"
BLOCKED_GOLDEN_BASELINE_MODIFIED_IN_PR: Final[str] = "BLOCKED-GOLDEN-BASELINE-MODIFIED-IN-PR"
BLOCKED_PHASE2_REPO_DISCOVERY: Final[str] = "BLOCKED-Phase2-RepoDiscovery"

# ---------------------------------------------------------------------------
# Kernel BLOCKED codes — install subsystem
# ---------------------------------------------------------------------------
BLOCKED_INSTALL_PRECHECK_MISSING_SOURCE: Final[str] = "BLOCKED-INSTALL-PRECHECK-MISSING-SOURCE"
BLOCKED_INSTALL_VERSION_MISSING: Final[str] = "BLOCKED-INSTALL-VERSION-MISSING"
BLOCKED_INSTALL_CONFIG_ROOT_INVALID: Final[str] = "BLOCKED-INSTALL-CONFIG-ROOT-INVALID"

# ---------------------------------------------------------------------------
# Profile/addon BLOCKED codes (profiles/*.md)
# ---------------------------------------------------------------------------
BLOCKED_MISSING_DB_VERSION: Final[str] = "BLOCKED-MISSING-DB-VERSION"
BLOCKED_FORMAT_UNDEFINED: Final[str] = "BLOCKED-FORMAT-UNDEFINED"
BLOCKED_MIGRATION_UNSAFE: Final[str] = "BLOCKED-MIGRATION-UNSAFE"
BLOCKED_MIGRATION_NO_ROLLBACK: Final[str] = "BLOCKED-MIGRATION-NO-ROLLBACK"
BLOCKED_MIGRATION_COMPATIBILITY: Final[str] = "BLOCKED-MIGRATION-COMPATIBILITY"

# ---------------------------------------------------------------------------
# WARN codes — kernel
# ---------------------------------------------------------------------------
WARN_UNMAPPED_AUDIT_REASON: Final[str] = "WARN-UNMAPPED-AUDIT-REASON"
WARN_WORKSPACE_PERSISTENCE: Final[str] = "WARN-WORKSPACE-PERSISTENCE"
WARN_ENGINE_LIVE_DENIED: Final[str] = "WARN-ENGINE-LIVE-DENIED"
WARN_MODE_DOWNGRADED: Final[str] = "WARN-MODE-DOWNGRADED"
WARN_PERMISSION_LIMITED: Final[str] = "WARN-PERMISSION-LIMITED"
WARN_SESSION_STATE_LEGACY_COMPAT_MODE: Final[str] = "WARN-SESSION-STATE-LEGACY-COMPAT-MODE"

# ---------------------------------------------------------------------------
# WARN codes — profile/addon domains
# ---------------------------------------------------------------------------
WARN_DOCS_README_DRIFT: Final[str] = "WARN-DOCS-README-DRIFT"
WARN_DOCS_SCHEMA_DRIFT: Final[str] = "WARN-DOCS-SCHEMA-DRIFT"
WARN_DOCS_MANIFEST_RULEBOOK_MISSING: Final[str] = "WARN-DOCS-MANIFEST-RULEBOOK-MISSING"
WARN_FALLBACK_BASELINE_UNKNOWN: Final[str] = "WARN-FALLBACK-BASELINE-UNKNOWN"
WARN_FALLBACK_TESTING_INSUFFICIENT: Final[str] = "WARN-FALLBACK-TESTING-INSUFFICIENT"
WARN_FALLBACK_RECOVERY_UNSPECIFIED: Final[str] = "WARN-FALLBACK-RECOVERY-UNSPECIFIED"
WARN_PRINCIPAL_EVIDENCE_MISSING: Final[str] = "WARN-PRINCIPAL-EVIDENCE-MISSING"
WARN_SCORECARD_CALIBRATION_INCOMPLETE: Final[str] = "WARN-SCORECARD-CALIBRATION-INCOMPLETE"
WARN_RISK_TIER_UNRESOLVED: Final[str] = "WARN-RISK-TIER-UNRESOLVED"
WARN_OPENAPI_SPEC_IMPLEMENTATION_MISMATCH: Final[str] = "WARN-OPENAPI-SPEC-IMPLEMENTATION-MISMATCH"
WARN_OPENAPI_VERSION_UNKNOWN: Final[str] = "WARN-OPENAPI-VERSION-UNKNOWN"
WARN_OPENAPI_MISSING_SPEC: Final[str] = "WARN-OPENAPI-MISSING-SPEC"
WARN_OPENAPI_BREAKING_CHANGE_UNAPPROVED: Final[str] = "WARN-OPENAPI-BREAKING-CHANGE-UNAPPROVED"
WARN_FE_OPENAPI_GENERATOR_UNKNOWN: Final[str] = "WARN-FE-OPENAPI-GENERATOR-UNKNOWN"
WARN_FE_OPENAPI_DRIFT_RISK: Final[str] = "WARN-FE-OPENAPI-DRIFT-RISK"
WARN_FE_OPENAPI_NO_NEGATIVE_TEST: Final[str] = "WARN-FE-OPENAPI-NO-NEGATIVE-TEST"
WARN_FE_OPENAPI_SOURCE_UNRESOLVED: Final[str] = "WARN-FE-OPENAPI-SOURCE-UNRESOLVED"
WARN_FE_OPENAPI_MAPPING_DRIFT_RISK: Final[str] = "WARN-FE-OPENAPI-MAPPING-DRIFT-RISK"
WARN_FE_OPENAPI_CONTRACT_TEST_MISSING: Final[str] = "WARN-FE-OPENAPI-CONTRACT-TEST-MISSING"
WARN_KAFKA_IDEMPOTENCY_UNVERIFIED: Final[str] = "WARN-KAFKA-IDEMPOTENCY-UNVERIFIED"
WARN_KAFKA_RETRY_POLICY_UNKNOWN: Final[str] = "WARN-KAFKA-RETRY-POLICY-UNKNOWN"
WARN_KAFKA_ASYNC_FLAKINESS_RISK: Final[str] = "WARN-KAFKA-ASYNC-FLAKINESS-RISK"
WARN_CYPRESS_FLAKY_RISK: Final[str] = "WARN-CYPRESS-FLAKY-RISK"
WARN_CYPRESS_SELECTOR_UNSTABLE: Final[str] = "WARN-CYPRESS-SELECTOR-UNSTABLE"
WARN_CYPRESS_NO_CRITICAL_FLOW_COVERAGE: Final[str] = "WARN-CYPRESS-NO-CRITICAL-FLOW-COVERAGE"
WARN_CYPRESS_NETWORK_CONTROL_MISSING: Final[str] = "WARN-CYPRESS-NETWORK-CONTROL-MISSING"
WARN_CYPRESS_CRITICAL_PATH_MISSING: Final[str] = "WARN-CYPRESS-CRITICAL-PATH-MISSING"
WARN_CYPRESS_ASYNC_FLAKE_RISK: Final[str] = "WARN-CYPRESS-ASYNC-FLAKE-RISK"
WARN_CUCUMBER_VERSION_UNKNOWN: Final[str] = "WARN-CUCUMBER-VERSION-UNKNOWN"
WARN_CUCUMBER_RUNNER_UNKNOWN: Final[str] = "WARN-CUCUMBER-RUNNER-UNKNOWN"
WARN_CUCUMBER_CONVENTIONS_UNKNOWN: Final[str] = "WARN-CUCUMBER-CONVENTIONS-UNKNOWN"
WARN_CUCUMBER_FLAKINESS_RISK: Final[str] = "WARN-CUCUMBER-FLAKINESS-RISK"
WARN_CUCUMBER_NO_EVIDENCE: Final[str] = "WARN-CUCUMBER-NO-EVIDENCE"
WARN_JAVA_DETERMINISM_RISK: Final[str] = "WARN-JAVA-DETERMINISM-RISK"

# ---------------------------------------------------------------------------
# NOT_VERIFIED codes
# ---------------------------------------------------------------------------
NOT_VERIFIED_MISSING_EVIDENCE: Final[str] = "NOT_VERIFIED-MISSING-EVIDENCE"
NOT_VERIFIED_EVIDENCE_STALE: Final[str] = "NOT_VERIFIED-EVIDENCE-STALE"

# ---------------------------------------------------------------------------
# Operational / informational codes
# ---------------------------------------------------------------------------
REPO_DOC_UNSAFE_DIRECTIVE: Final[str] = "REPO-DOC-UNSAFE-DIRECTIVE"
REPO_CONSTRAINT_WIDENING: Final[str] = "REPO-CONSTRAINT-WIDENING"
REPO_CONSTRAINT_UNSUPPORTED: Final[str] = "REPO-CONSTRAINT-UNSUPPORTED"
INTERACTIVE_REQUIRED_IN_PIPELINE: Final[str] = "INTERACTIVE-REQUIRED-IN-PIPELINE"
PROMPT_BUDGET_EXCEEDED: Final[str] = "PROMPT-BUDGET-EXCEEDED"
POLICY_PRECEDENCE_APPLIED: Final[str] = "POLICY-PRECEDENCE-APPLIED"

# ---------------------------------------------------------------------------
# Persistence gate codes
# ---------------------------------------------------------------------------
PERSIST_CONFIRMATION_REQUIRED: Final[str] = "PERSIST_CONFIRMATION_REQUIRED"
PERSIST_CONFIRMATION_INVALID: Final[str] = "PERSIST_CONFIRMATION_INVALID"
PERSIST_DISALLOWED_IN_PIPELINE: Final[str] = "PERSIST_DISALLOWED_IN_PIPELINE"
PERSIST_PHASE_MISMATCH: Final[str] = "PERSIST_PHASE_MISMATCH"
PERSIST_GATE_NOT_APPROVED: Final[str] = "PERSIST_GATE_NOT_APPROVED"

# ---------------------------------------------------------------------------
# Aliases / backward-compat
# ---------------------------------------------------------------------------
DEFAULT_UNMAPPED_AUDIT_REASON: Final[str] = WARN_UNMAPPED_AUDIT_REASON

# ---------------------------------------------------------------------------
# Parameterized reason code prefixes
# ---------------------------------------------------------------------------
_PARAMETERIZED_PREFIXES: Final[tuple[str, ...]] = (
    "BLOCKED-MISSING-ADDON:",
    "BLOCKED-MISSING-RULEBOOK:",
    "BLOCKED-ADDON-CONFLICT:",
)

# ---------------------------------------------------------------------------
# Canonical membership set
# ---------------------------------------------------------------------------
CANONICAL_REASON_CODES: Final[tuple[str, ...]] = (
    # Kernel BLOCKED
    BLOCKED_BOOTSTRAP_NOT_SATISFIED,
    BLOCKED_START_REQUIRED,
    BLOCKED_MISSING_CORE_RULES,
    BLOCKED_MISSING_PROFILE,
    BLOCKED_AMBIGUOUS_PROFILE,
    BLOCKED_MISSING_DECISION,
    BLOCKED_MISSING_TEMPLATES,
    BLOCKED_MISSING_RULEBOOK,
    BLOCKED_MISSING_ADDON,
    BLOCKED_ADDON_CONFLICT,
    BLOCKED_ACTIVATION_DELTA_MISMATCH,
    BLOCKED_RULEBOOK_EVIDENCE_MISSING,
    BLOCKED_WORKSPACE_MEMORY_INVALID,
    BLOCKED_MISSING_EVIDENCE,
    BLOCKED_RESUME_STATE_VIOLATION,
    BLOCKED_MISSING_BINDING_FILE,
    BLOCKED_VARIABLE_RESOLUTION,
    BLOCKED_WORKSPACE_PERSISTENCE,
    BLOCKED_ENGINE_SELFCHECK,
    BLOCKED_REPO_IDENTITY_RESOLUTION,
    BLOCKED_SYSTEM_MODE_REQUIRED,
    BLOCKED_OPERATING_MODE_REQUIRED,
    BLOCKED_STATE_OUTDATED,
    BLOCKED_PACK_LOCK_REQUIRED,
    BLOCKED_PACK_LOCK_INVALID,
    BLOCKED_PACK_LOCK_MISMATCH,
    BLOCKED_SURFACE_CONFLICT,
    BLOCKED_RULESET_HASH_MISMATCH,
    BLOCKED_ACTIVATION_HASH_MISMATCH,
    BLOCKED_RELEASE_HYGIENE,
    BLOCKED_SESSION_STATE_LEGACY_UNSUPPORTED,
    BLOCKED_UNSPECIFIED,
    BLOCKED_PERSISTENCE_TARGET_DEGENERATE,
    BLOCKED_PERSISTENCE_PATH_VIOLATION,
    BLOCKED_PERMISSION_DENIED,
    BLOCKED_EXEC_DISALLOWED,
    BLOCKED_FINGERPRINT_MISMATCH,
    BLOCKED_GOLDEN_BASELINE_MODIFIED_IN_PR,
    BLOCKED_PHASE2_REPO_DISCOVERY,
    # Install subsystem
    BLOCKED_INSTALL_PRECHECK_MISSING_SOURCE,
    BLOCKED_INSTALL_VERSION_MISSING,
    BLOCKED_INSTALL_CONFIG_ROOT_INVALID,
    # Profile/addon BLOCKED
    BLOCKED_MISSING_DB_VERSION,
    BLOCKED_FORMAT_UNDEFINED,
    BLOCKED_MIGRATION_UNSAFE,
    BLOCKED_MIGRATION_NO_ROLLBACK,
    BLOCKED_MIGRATION_COMPATIBILITY,
    # WARN — kernel
    WARN_UNMAPPED_AUDIT_REASON,
    WARN_WORKSPACE_PERSISTENCE,
    WARN_ENGINE_LIVE_DENIED,
    WARN_MODE_DOWNGRADED,
    WARN_PERMISSION_LIMITED,
    WARN_SESSION_STATE_LEGACY_COMPAT_MODE,
    # WARN — profile/addon
    WARN_DOCS_README_DRIFT,
    WARN_DOCS_SCHEMA_DRIFT,
    WARN_DOCS_MANIFEST_RULEBOOK_MISSING,
    WARN_FALLBACK_BASELINE_UNKNOWN,
    WARN_FALLBACK_TESTING_INSUFFICIENT,
    WARN_FALLBACK_RECOVERY_UNSPECIFIED,
    WARN_PRINCIPAL_EVIDENCE_MISSING,
    WARN_SCORECARD_CALIBRATION_INCOMPLETE,
    WARN_RISK_TIER_UNRESOLVED,
    WARN_OPENAPI_SPEC_IMPLEMENTATION_MISMATCH,
    WARN_OPENAPI_VERSION_UNKNOWN,
    WARN_OPENAPI_MISSING_SPEC,
    WARN_OPENAPI_BREAKING_CHANGE_UNAPPROVED,
    WARN_FE_OPENAPI_GENERATOR_UNKNOWN,
    WARN_FE_OPENAPI_DRIFT_RISK,
    WARN_FE_OPENAPI_NO_NEGATIVE_TEST,
    WARN_FE_OPENAPI_SOURCE_UNRESOLVED,
    WARN_FE_OPENAPI_MAPPING_DRIFT_RISK,
    WARN_FE_OPENAPI_CONTRACT_TEST_MISSING,
    WARN_KAFKA_IDEMPOTENCY_UNVERIFIED,
    WARN_KAFKA_RETRY_POLICY_UNKNOWN,
    WARN_KAFKA_ASYNC_FLAKINESS_RISK,
    WARN_CYPRESS_FLAKY_RISK,
    WARN_CYPRESS_SELECTOR_UNSTABLE,
    WARN_CYPRESS_NO_CRITICAL_FLOW_COVERAGE,
    WARN_CYPRESS_NETWORK_CONTROL_MISSING,
    WARN_CYPRESS_CRITICAL_PATH_MISSING,
    WARN_CYPRESS_ASYNC_FLAKE_RISK,
    WARN_CUCUMBER_VERSION_UNKNOWN,
    WARN_CUCUMBER_RUNNER_UNKNOWN,
    WARN_CUCUMBER_CONVENTIONS_UNKNOWN,
    WARN_CUCUMBER_FLAKINESS_RISK,
    WARN_CUCUMBER_NO_EVIDENCE,
    WARN_JAVA_DETERMINISM_RISK,
    # NOT_VERIFIED
    NOT_VERIFIED_MISSING_EVIDENCE,
    NOT_VERIFIED_EVIDENCE_STALE,
    # Operational
    REPO_DOC_UNSAFE_DIRECTIVE,
    REPO_CONSTRAINT_WIDENING,
    REPO_CONSTRAINT_UNSUPPORTED,
    INTERACTIVE_REQUIRED_IN_PIPELINE,
    PROMPT_BUDGET_EXCEEDED,
    POLICY_PRECEDENCE_APPLIED,
    # Persistence gate
    PERSIST_CONFIRMATION_REQUIRED,
    PERSIST_CONFIRMATION_INVALID,
    PERSIST_DISALLOWED_IN_PIPELINE,
    PERSIST_PHASE_MISMATCH,
    PERSIST_GATE_NOT_APPROVED,
)


def is_registered_reason_code(reason_code: str, *, allow_none: bool = True) -> bool:
    """Check exact membership in the canonical registry."""
    normalized = reason_code.strip()
    if allow_none and normalized == REASON_CODE_NONE:
        return True
    return normalized in CANONICAL_REASON_CODES


def is_registered_reason_code_or_parameterized(
    reason_code: str, *, allow_none: bool = True
) -> bool:
    """Check membership including parameterized codes (e.g. ``BLOCKED-MISSING-ADDON:<key>``)."""
    if is_registered_reason_code(reason_code, allow_none=allow_none):
        return True
    normalized = reason_code.strip()
    return any(normalized.startswith(prefix) for prefix in _PARAMETERIZED_PREFIXES)


REASON_CODE_HINTS: Final[dict[str, str]] = {
    BLOCKED_INSTALL_PRECHECK_MISSING_SOURCE: (
        "Required governance source files are missing. "
        "If installing from source: clone the repository. "
        "If using a bundle: extract it first, then run install.py from the extracted directory. "
        "If already installed: run '${PYTHON_COMMAND} install.py --status' to check installation health."
    ),
    BLOCKED_INSTALL_VERSION_MISSING: (
        "Governance version not found in master.md. "
        "Ensure master.md contains 'Governance-Version: <semver>' header."
    ),
    BLOCKED_INSTALL_CONFIG_ROOT_INVALID: (
        "Config root path is invalid or not writable. "
        "Check path permissions and try again."
    ),
}
