"""Canonical governance reason-code registry.

SSOT for all reason codes referenced by kernel-owned configs/schemas and
profile/addon rulebooks.

Every reason code used in any governance surface MUST have a constant here.
The ``CANONICAL_REASON_CODES`` tuple is the single authoritative membership set
used by ``is_registered_reason_code()``.

Parameterized codes (e.g. BLOCKED-MISSING-ADDON:<key>) use a prefix-match helper
``is_registered_reason_code_or_parameterized()`` for runtime validation.
"""

from __future__ import annotations

from typing import Final

# ---------------------------------------------------------------------------
# Meta
# ---------------------------------------------------------------------------
REASON_CODE_NONE: Final[str] = "none"

# ---------------------------------------------------------------------------
# Kernel BLOCKED codes (kernel-owned policy bundle)
# ---------------------------------------------------------------------------
BLOCKED_BOOTSTRAP_NOT_SATISFIED: Final[str] = "BLOCKED-BOOTSTRAP-NOT-SATISFIED"
BLOCKED_START_REQUIRED: Final[str] = "BLOCKED-START-REQUIRED"
BLOCKED_MISSING_CORE_RULES: Final[str] = "BLOCKED-MISSING-CORE-RULES"
BLOCKED_RULEBOOK_LOAD_FAILED: Final[str] = "BLOCKED-RULEBOOK-LOAD-FAILED"
BLOCKED_MISSING_PROFILE: Final[str] = "BLOCKED-MISSING-PROFILE"
BLOCKED_AMBIGUOUS_PROFILE: Final[str] = "BLOCKED-AMBIGUOUS-PROFILE"
BLOCKED_MISSING_DECISION: Final[str] = "BLOCKED-MISSING-DECISION"
BLOCKED_MISSING_TEMPLATES: Final[str] = "BLOCKED-MISSING-TEMPLATES"
BLOCKED_MISSING_RULEBOOK: Final[str] = "BLOCKED-MISSING-RULEBOOK"
BLOCKED_MISSING_ADDON: Final[str] = "BLOCKED-MISSING-ADDON"
BLOCKED_ADDON_CONFLICT: Final[str] = "BLOCKED-ADDON-CONFLICT"
BLOCKED_ACTIVATION_DELTA_MISMATCH: Final[str] = "BLOCKED-ACTIVATION-DELTA-MISMATCH"
BLOCKED_RULEBOOK_EVIDENCE_MISSING: Final[str] = "BLOCKED-RULEBOOK-EVIDENCE-MISSING"
BLOCKED_WORKSPACE_MEMORY_INVALID: Final[str] = "BLOCKED-WORKSPACE-MEMORY-INVALID"
BLOCKED_MISSING_EVIDENCE: Final[str] = "BLOCKED-MISSING-EVIDENCE"
BLOCKED_RESUME_STATE_VIOLATION: Final[str] = "BLOCKED-RESUME-STATE-VIOLATION"
BLOCKED_MISSING_BINDING_FILE: Final[str] = "BLOCKED-MISSING-BINDING-FILE"
BLOCKED_MISSING_COMMANDS_HOME: Final[str] = "BLOCKED-MISSING-COMMANDS-HOME"
BLOCKED_VARIABLE_RESOLUTION: Final[str] = "BLOCKED-VARIABLE-RESOLUTION"
BLOCKED_WORKSPACE_PERSISTENCE: Final[str] = "BLOCKED-WORKSPACE-PERSISTENCE"
BLOCKED_ENGINE_SELFCHECK: Final[str] = "BLOCKED-ENGINE-SELFCHECK"
BLOCKED_REPO_IDENTITY_RESOLUTION: Final[str] = "BLOCKED-REPO-IDENTITY-RESOLUTION"
BLOCKED_SYSTEM_MODE_REQUIRED: Final[str] = "BLOCKED-SYSTEM-MODE-REQUIRED"
BLOCKED_OPERATING_MODE_REQUIRED: Final[str] = "BLOCKED-OPERATING-MODE-REQUIRED"
BLOCKED_STATE_OUTDATED: Final[str] = "BLOCKED-STATE-OUTDATED"
BLOCKED_PACK_LOCK_REQUIRED: Final[str] = "BLOCKED-PACK-LOCK-REQUIRED"
BLOCKED_PACK_LOCK_INVALID: Final[str] = "BLOCKED-PACK-LOCK-INVALID"
BLOCKED_PACK_LOCK_MISMATCH: Final[str] = "BLOCKED-PACK-LOCK-MISMATCH"
BLOCKED_SURFACE_CONFLICT: Final[str] = "BLOCKED-SURFACE-CONFLICT"
BLOCKED_RULESET_HASH_MISMATCH: Final[str] = "BLOCKED-RULESET-HASH-MISMATCH"
BLOCKED_ACTIVATION_HASH_MISMATCH: Final[str] = "BLOCKED-ACTIVATION-HASH-MISMATCH"
BLOCKED_RELEASE_HYGIENE: Final[str] = "BLOCKED-RELEASE-HYGIENE"
BLOCKED_SESSION_STATE_LEGACY_UNSUPPORTED: Final[str] = "BLOCKED-SESSION-STATE-LEGACY-UNSUPPORTED"
BLOCKED_UNSPECIFIED: Final[str] = "BLOCKED-UNSPECIFIED"
BLOCKED_PERSISTENCE_TARGET_DEGENERATE: Final[str] = "BLOCKED-PERSISTENCE-TARGET-DEGENERATE"
BLOCKED_PERSISTENCE_PATH_VIOLATION: Final[str] = "BLOCKED-PERSISTENCE-PATH-VIOLATION"
BLOCKED_PERMISSION_DENIED: Final[str] = "BLOCKED-PERMISSION-DENIED"
BLOCKED_EXEC_DISALLOWED: Final[str] = "BLOCKED-EXEC-DISALLOWED"
BLOCKED_FINGERPRINT_MISMATCH: Final[str] = "BLOCKED-FINGERPRINT-MISMATCH"
BLOCKED_INTEGRITY_FAILED: Final[str] = "BLOCKED-INTEGRITY-FAILED"
BLOCKED_REPO_ROOT_NOT_DETECTABLE: Final[str] = "BLOCKED-REPO-ROOT-NOT-DETECTABLE"
BLOCKED_LEGACY_DECISION_PACK_FORMAT: Final[str] = "BLOCKED-LEGACY-DECISION-PACK-FORMAT"
BLOCKED_INVALID_NEXT_ACTION: Final[str] = "BLOCKED-INVALID-NEXT-ACTION"
BLOCKED_GOLDEN_BASELINE_MODIFIED_IN_PR: Final[str] = "BLOCKED-GOLDEN-BASELINE-MODIFIED-IN-PR"
BLOCKED_REPO_DISCOVERY: Final[str] = "BLOCKED-2-REPO-DISCOVERY"
BLOCKED_RECOVERY_REQUIRED: Final[str] = "BLOCKED-R"
BLOCKED_P5_3_TEST_QUALITY_GATE: Final[str] = "BLOCKED-P5-3-TEST-QUALITY-GATE"
BLOCKED_P5_4_BUSINESS_RULES_GATE: Final[str] = "BLOCKED-P5-4-BUSINESS-RULES-GATE"
BLOCKED_P5_5_TECHNICAL_DEBT_GATE: Final[str] = "BLOCKED-P5-5-TECHNICAL-DEBT-GATE"
BLOCKED_P5_6_ROLLBACK_SAFETY_GATE: Final[str] = "BLOCKED-P5-6-ROLLBACK-SAFETY-GATE"
BLOCKED_P4_INTAKE_MISSING_EVIDENCE: Final[str] = "BLOCKED-P4-INTAKE-MISSING-EVIDENCE"
BLOCKED_P5_PLAN_RECORD_PERSIST: Final[str] = "BLOCKED-P5-PLAN-RECORD-PERSIST"
BLOCKED_P5_PHASE_MISMATCH: Final[str] = "BLOCKED-P5-PHASE-MISMATCH"
BLOCKED_P5_TICKET_EVIDENCE_MISSING: Final[str] = "BLOCKED-P5-TICKET-EVIDENCE-MISSING"
BLOCKED_P5_PLAN_EMPTY: Final[str] = "BLOCKED-P5-PLAN-EMPTY"
BLOCKED_P5_REVIEW_PERSIST_FAILED: Final[str] = "BLOCKED-P5-REVIEW-PERSIST-FAILED"
BLOCKED_P6_PREREQUISITES_NOT_MET: Final[str] = "BLOCKED-P6-PREREQUISITES-NOT-MET"
BLOCKED_P6_PLAN_COMPLIANCE_MAJOR: Final[str] = "BLOCKED-P6-PLAN-COMPLIANCE-MAJOR"
BLOCKED_REVIEW_DECISION_INVALID: Final[str] = "BLOCKED-REVIEW-DECISION-INVALID"
WARN_P6_PLAN_COMPLIANCE_DRIFT: Final[str] = "WARN-P6-PLAN-COMPLIANCE-DRIFT"
BLOCKED_PIPELINE_INTERACTIVE: Final[str] = "BLOCKED-PIPELINE-INTERACTIVE"
BLOCKED_PIPELINE_HUMAN_ASSIST: Final[str] = "BLOCKED-PIPELINE-HUMAN-ASSIST"
BLOCKED_PIPELINE_PROMPT_BUDGET: Final[str] = "BLOCKED-PIPELINE-PROMPT-BUDGET"
BLOCKED_RECEIPT_MISSING_TYPE: Final[str] = "BLOCKED-RECEIPT-MISSING-TYPE"
BLOCKED_RECEIPT_MISSING_GATE: Final[str] = "BLOCKED-RECEIPT-MISSING-GATE"
BLOCKED_RECEIPT_MISSING_DIGEST: Final[str] = "BLOCKED-RECEIPT-MISSING-DIGEST"
BLOCKED_RECEIPT_MISSING_SESSION: Final[str] = "BLOCKED-RECEIPT-MISSING-SESSION"
BLOCKED_RECEIPT_MISSING_STATE_REVISION: Final[str] = "BLOCKED-RECEIPT-MISSING-STATE-REVISION"
BLOCKED_RECEIPT_MISSING_SCOPE: Final[str] = "BLOCKED-RECEIPT-MISSING-SCOPE"
BLOCKED_RECEIPT_MISSING_TIMESTAMP: Final[str] = "BLOCKED-RECEIPT-MISSING-TIMESTAMP"
BLOCKED_RECEIPT_TYPE_MISMATCH: Final[str] = "BLOCKED-RECEIPT-TYPE-MISMATCH"
BLOCKED_RECEIPT_GATE_MISMATCH: Final[str] = "BLOCKED-RECEIPT-GATE-MISMATCH"
BLOCKED_RECEIPT_DIGEST_MISMATCH: Final[str] = "BLOCKED-RECEIPT-DIGEST-MISMATCH"
BLOCKED_RECEIPT_SESSION_MISMATCH: Final[str] = "BLOCKED-RECEIPT-SESSION-MISMATCH"
BLOCKED_RECEIPT_STATE_REVISION_MISMATCH: Final[str] = "BLOCKED-RECEIPT-STATE-REVISION-MISMATCH"
BLOCKED_RECEIPT_SCOPE_MISMATCH: Final[str] = "BLOCKED-RECEIPT-SCOPE-MISMATCH"
BLOCKED_RECEIPT_INVALID_TIMESTAMP: Final[str] = "BLOCKED-RECEIPT-INVALID-TIMESTAMP"
BLOCKED_RECEIPT_STALE_TIMESTAMP: Final[str] = "BLOCKED-RECEIPT-STALE-TIMESTAMP"

# ---------------------------------------------------------------------------
# Kernel BLOCKED codes — model identity
# ---------------------------------------------------------------------------
BLOCKED_MODEL_IDENTITY_UNTRUSTED: Final[str] = "BLOCKED-MODEL-IDENTITY-UNTRUSTED"
BLOCKED_MODEL_CONTEXT_LIMIT_REQUIRED: Final[str] = "BLOCKED-MODEL-CONTEXT-LIMIT-REQUIRED"
BLOCKED_MODEL_CONTEXT_LIMIT_UNKNOWN: Final[str] = "BLOCKED-MODEL-CONTEXT-LIMIT-UNKNOWN"
BLOCKED_MODEL_CONTEXT_LIMIT_INVALID: Final[str] = "BLOCKED-MODEL-CONTEXT-LIMIT-INVALID"
BLOCKED_MODEL_METADATA_FETCH_FAILED: Final[str] = "BLOCKED-MODEL-METADATA-FETCH-FAILED"
BLOCKED_MODEL_IDENTITY_SOURCE_INVALID: Final[str] = "BLOCKED-MODEL-IDENTITY-SOURCE-INVALID"

# ---------------------------------------------------------------------------
# Kernel BLOCKED codes — install subsystem
# ---------------------------------------------------------------------------
BLOCKED_INSTALL_PRECHECK_MISSING_SOURCE: Final[str] = "BLOCKED-INSTALL-PRECHECK-MISSING-SOURCE"
BLOCKED_INSTALL_VERSION_MISSING: Final[str] = "BLOCKED-INSTALL-VERSION-MISSING"
BLOCKED_INSTALL_CONFIG_ROOT_INVALID: Final[str] = "BLOCKED-INSTALL-CONFIG-ROOT-INVALID"

# ---------------------------------------------------------------------------
# Kernel BLOCKED codes — contract drift
# ---------------------------------------------------------------------------
BLOCKED_CONTRACT_LAYOUT_DRIFT: Final[str] = "BLOCKED-CONTRACT-LAYOUT-DRIFT"
BLOCKED_CONTRACT_RUNTIME_DRIFT: Final[str] = "BLOCKED-CONTRACT-RUNTIME-DRIFT"
BLOCKED_CONTRACT_OPENCODE_DRIFT: Final[str] = "BLOCKED-CONTRACT-OPENCODE-DRIFT"

# ---------------------------------------------------------------------------
# Profile/addon BLOCKED codes (profiles/*.md)
# ---------------------------------------------------------------------------
BLOCKED_MISSING_DB_VERSION: Final[str] = "BLOCKED-MISSING-DB-VERSION"
BLOCKED_FORMAT_UNDEFINED: Final[str] = "BLOCKED-FORMAT-UNDEFINED"
BLOCKED_MIGRATION_UNSAFE: Final[str] = "BLOCKED-MIGRATION-UNSAFE"
BLOCKED_MIGRATION_NO_ROLLBACK: Final[str] = "BLOCKED-MIGRATION-NO-ROLLBACK"
BLOCKED_MIGRATION_COMPATIBILITY: Final[str] = "BLOCKED-MIGRATION-COMPATIBILITY"

# ---------------------------------------------------------------------------
# WARN codes — kernel
# ---------------------------------------------------------------------------
WARN_UNMAPPED_AUDIT_REASON: Final[str] = "WARN-UNMAPPED-AUDIT-REASON"
WARN_WORKSPACE_PERSISTENCE: Final[str] = "WARN-WORKSPACE-PERSISTENCE"
WARN_ENGINE_LIVE_DENIED: Final[str] = "WARN-ENGINE-LIVE-DENIED"
WARN_MODE_DOWNGRADED: Final[str] = "WARN-MODE-DOWNGRADED"
WARN_PERMISSION_LIMITED: Final[str] = "WARN-PERMISSION-LIMITED"
WARN_SESSION_STATE_LEGACY_COMPAT_MODE: Final[str] = "WARN-SESSION-STATE-LEGACY-COMPAT-MODE"
WARN_P6_STATE_INCONSISTENCY: Final[str] = "WARN-P6-STATE-INCONSISTENCY"

# ---------------------------------------------------------------------------
# WARN codes — profile/addon domains
# ---------------------------------------------------------------------------
WARN_DOCS_README_DRIFT: Final[str] = "WARN-DOCS-README-DRIFT"
WARN_DOCS_SCHEMA_DRIFT: Final[str] = "WARN-DOCS-SCHEMA-DRIFT"
WARN_DOCS_MANIFEST_RULEBOOK_MISSING: Final[str] = "WARN-DOCS-MANIFEST-RULEBOOK-MISSING"
WARN_FALLBACK_BASELINE_UNKNOWN: Final[str] = "WARN-FALLBACK-BASELINE-UNKNOWN"
WARN_FALLBACK_TESTING_INSUFFICIENT: Final[str] = "WARN-FALLBACK-TESTING-INSUFFICIENT"
WARN_FALLBACK_RECOVERY_UNSPECIFIED: Final[str] = "WARN-FALLBACK-RECOVERY-UNSPECIFIED"
WARN_PRINCIPAL_EVIDENCE_MISSING: Final[str] = "WARN-PRINCIPAL-EVIDENCE-MISSING"
WARN_SCORECARD_CALIBRATION_INCOMPLETE: Final[str] = "WARN-SCORECARD-CALIBRATION-INCOMPLETE"
WARN_RISK_TIER_UNRESOLVED: Final[str] = "WARN-RISK-TIER-UNRESOLVED"
WARN_OPENAPI_SPEC_IMPLEMENTATION_MISMATCH: Final[str] = "WARN-OPENAPI-SPEC-IMPLEMENTATION-MISMATCH"
WARN_OPENAPI_VERSION_UNKNOWN: Final[str] = "WARN-OPENAPI-VERSION-UNKNOWN"
WARN_OPENAPI_MISSING_SPEC: Final[str] = "WARN-OPENAPI-MISSING-SPEC"
WARN_OPENAPI_BREAKING_CHANGE_UNAPPROVED: Final[str] = "WARN-OPENAPI-BREAKING-CHANGE-UNAPPROVED"
WARN_FE_OPENAPI_GENERATOR_UNKNOWN: Final[str] = "WARN-FE-OPENAPI-GENERATOR-UNKNOWN"
WARN_FE_OPENAPI_DRIFT_RISK: Final[str] = "WARN-FE-OPENAPI-DRIFT-RISK"
WARN_FE_OPENAPI_NO_NEGATIVE_TEST: Final[str] = "WARN-FE-OPENAPI-NO-NEGATIVE-TEST"
WARN_FE_OPENAPI_SOURCE_UNRESOLVED: Final[str] = "WARN-FE-OPENAPI-SOURCE-UNRESOLVED"
WARN_FE_OPENAPI_MAPPING_DRIFT_RISK: Final[str] = "WARN-FE-OPENAPI-MAPPING-DRIFT-RISK"
WARN_FE_OPENAPI_CONTRACT_TEST_MISSING: Final[str] = "WARN-FE-OPENAPI-CONTRACT-TEST-MISSING"
WARN_KAFKA_IDEMPOTENCY_UNVERIFIED: Final[str] = "WARN-KAFKA-IDEMPOTENCY-UNVERIFIED"
WARN_KAFKA_RETRY_POLICY_UNKNOWN: Final[str] = "WARN-KAFKA-RETRY-POLICY-UNKNOWN"
WARN_KAFKA_ASYNC_FLAKINESS_RISK: Final[str] = "WARN-KAFKA-ASYNC-FLAKINESS-RISK"
WARN_CYPRESS_FLAKY_RISK: Final[str] = "WARN-CYPRESS-FLAKY-RISK"
WARN_CYPRESS_SELECTOR_UNSTABLE: Final[str] = "WARN-CYPRESS-SELECTOR-UNSTABLE"
WARN_CYPRESS_NO_CRITICAL_FLOW_COVERAGE: Final[str] = "WARN-CYPRESS-NO-CRITICAL-FLOW-COVERAGE"
WARN_CYPRESS_NETWORK_CONTROL_MISSING: Final[str] = "WARN-CYPRESS-NETWORK-CONTROL-MISSING"
WARN_CYPRESS_CRITICAL_PATH_MISSING: Final[str] = "WARN-CYPRESS-CRITICAL-PATH-MISSING"
WARN_CYPRESS_ASYNC_FLAKE_RISK: Final[str] = "WARN-CYPRESS-ASYNC-FLAKE-RISK"
WARN_CUCUMBER_VERSION_UNKNOWN: Final[str] = "WARN-CUCUMBER-VERSION-UNKNOWN"
WARN_CUCUMBER_RUNNER_UNKNOWN: Final[str] = "WARN-CUCUMBER-RUNNER-UNKNOWN"
WARN_CUCUMBER_CONVENTIONS_UNKNOWN: Final[str] = "WARN-CUCUMBER-CONVENTIONS-UNKNOWN"
WARN_CUCUMBER_FLAKINESS_RISK: Final[str] = "WARN-CUCUMBER-FLAKINESS-RISK"
WARN_CUCUMBER_NO_EVIDENCE: Final[str] = "WARN-CUCUMBER-NO-EVIDENCE"
WARN_JAVA_DETERMINISM_RISK: Final[str] = "WARN-JAVA-DETERMINISM-RISK"
WARN_BUILD_TOOL_MISSING: Final[str] = "WARN-BUILD-TOOL-MISSING"
WARN_ANGULAR_BOUNDARY_DRIFT: Final[str] = "WARN-ANGULAR-BOUNDARY-DRIFT"
WARN_ANGULAR_STATE_PATTERN_MIX: Final[str] = "WARN-ANGULAR-STATE-PATTERN-MIX"
WARN_ANGULAR_ASYNC_DETERMINISM: Final[str] = "WARN-ANGULAR-ASYNC-DETERMINISM"
WARN_PYTHON_MIGRATION_ROLLBACK_MISSING: Final[str] = "WARN-PYTHON-MIGRATION-ROLLBACK-MISSING"
WARN_PYTHON_ASYNC_DETERMINISM: Final[str] = "WARN-PYTHON-ASYNC-DETERMINISM"
WARN_PYTHON_TYPE_CHECK_SKIPPED: Final[str] = "WARN-PYTHON-TYPE-CHECK-SKIPPED"
WARN_LIQUIBASE_PG_VERSION_UNKNOWN: Final[str] = "WARN-LIQUIBASE-PG-VERSION-UNKNOWN"
WARN_LIQUIBASE_ROLLBACK_MISSING: Final[str] = "WARN-LIQUIBASE-ROLLBACK-MISSING"
WARN_LIQUIBASE_LOCK_RISK: Final[str] = "WARN-LIQUIBASE-LOCK-RISK"
WARN_LIQUIBASE_DATA_MIGRATION_UNVERIFIED: Final[str] = "WARN-LIQUIBASE-DATA-MIGRATION-UNVERIFIED"
WARN_SESSION_STATE_SCHEMA_VIOLATION: Final[str] = "WARN-SESSION-STATE-SCHEMA-VIOLATION"

# ---------------------------------------------------------------------------
# NOT_VERIFIED codes
# ---------------------------------------------------------------------------
NOT_VERIFIED_MISSING_EVIDENCE: Final[str] = "NOT_VERIFIED-MISSING-EVIDENCE"
NOT_VERIFIED_EVIDENCE_STALE: Final[str] = "NOT_VERIFIED-EVIDENCE-STALE"

# ---------------------------------------------------------------------------
# Strict-exit enforcement codes (principal_strict mode)
# ---------------------------------------------------------------------------
BLOCKED_STRICT_EVIDENCE_MISSING: Final[str] = "BLOCKED-STRICT-EVIDENCE-MISSING"
BLOCKED_STRICT_EVIDENCE_STALE: Final[str] = "BLOCKED-STRICT-EVIDENCE-STALE"
BLOCKED_STRICT_THRESHOLD: Final[str] = "BLOCKED-STRICT-THRESHOLD"
BLOCKED_STRICT_CONTRACT_MISSING: Final[str] = "BLOCKED-STRICT-CONTRACT-MISSING"
NOT_VERIFIED_STRICT_EVIDENCE_STALE: Final[str] = "NOT_VERIFIED-STRICT-EVIDENCE-STALE"
NOT_VERIFIED_STRICT_EVIDENCE_MISSING: Final[str] = "NOT_VERIFIED-STRICT-EVIDENCE-MISSING"

# ---------------------------------------------------------------------------
# Operational / informational codes
# ---------------------------------------------------------------------------
REPO_DOC_UNSAFE_DIRECTIVE: Final[str] = "REPO-DOC-UNSAFE-DIRECTIVE"
REPO_CONSTRAINT_WIDENING: Final[str] = "REPO-CONSTRAINT-WIDENING"
REPO_CONSTRAINT_UNSUPPORTED: Final[str] = "REPO-CONSTRAINT-UNSUPPORTED"
INTERACTIVE_REQUIRED_IN_PIPELINE: Final[str] = "INTERACTIVE-REQUIRED-IN-PIPELINE"
PROMPT_BUDGET_EXCEEDED: Final[str] = "PROMPT-BUDGET-EXCEEDED"
POLICY_PRECEDENCE_APPLIED: Final[str] = "POLICY-PRECEDENCE-APPLIED"

# ---------------------------------------------------------------------------
# Persistence gate codes
# ---------------------------------------------------------------------------
PERSIST_CONFIRMATION_REQUIRED: Final[str] = "PERSIST_CONFIRMATION_REQUIRED"
PERSIST_CONFIRMATION_INVALID: Final[str] = "PERSIST_CONFIRMATION_INVALID"
PERSIST_DISALLOWED_IN_PIPELINE: Final[str] = "PERSIST_DISALLOWED_IN_PIPELINE"
PERSIST_PHASE_MISMATCH: Final[str] = "PERSIST_PHASE_MISMATCH"
PERSIST_GATE_NOT_APPROVED: Final[str] = "PERSIST_GATE_NOT_APPROVED"

# ---------------------------------------------------------------------------
# Aliases / backward-compat
# ---------------------------------------------------------------------------
DEFAULT_UNMAPPED_AUDIT_REASON: Final[str] = WARN_UNMAPPED_AUDIT_REASON

# ---------------------------------------------------------------------------
# Parameterized reason code prefixes
# ---------------------------------------------------------------------------
_PARAMETERIZED_PREFIXES: Final[tuple[str, ...]] = (
    "BLOCKED-MISSING-ADDON:",
    "BLOCKED-MISSING-RULEBOOK:",
    "BLOCKED-ADDON-CONFLICT:",
)

# ---------------------------------------------------------------------------
# Canonical membership set
# ---------------------------------------------------------------------------
CANONICAL_REASON_CODES: Final[tuple[str, ...]] = (
    # Kernel BLOCKED
    BLOCKED_BOOTSTRAP_NOT_SATISFIED,
    BLOCKED_START_REQUIRED,
    BLOCKED_MISSING_CORE_RULES,
    BLOCKED_RULEBOOK_LOAD_FAILED,
    BLOCKED_MISSING_PROFILE,
    BLOCKED_AMBIGUOUS_PROFILE,
    BLOCKED_MISSING_DECISION,
    BLOCKED_MISSING_TEMPLATES,
    BLOCKED_MISSING_RULEBOOK,
    BLOCKED_MISSING_ADDON,
    BLOCKED_ADDON_CONFLICT,
    BLOCKED_ACTIVATION_DELTA_MISMATCH,
    BLOCKED_RULEBOOK_EVIDENCE_MISSING,
    BLOCKED_WORKSPACE_MEMORY_INVALID,
    BLOCKED_MISSING_EVIDENCE,
    BLOCKED_RESUME_STATE_VIOLATION,
    BLOCKED_MISSING_BINDING_FILE,
    BLOCKED_MISSING_COMMANDS_HOME,
    BLOCKED_VARIABLE_RESOLUTION,
    BLOCKED_WORKSPACE_PERSISTENCE,
    BLOCKED_ENGINE_SELFCHECK,
    BLOCKED_REPO_IDENTITY_RESOLUTION,
    BLOCKED_SYSTEM_MODE_REQUIRED,
    BLOCKED_OPERATING_MODE_REQUIRED,
    BLOCKED_STATE_OUTDATED,
    BLOCKED_PACK_LOCK_REQUIRED,
    BLOCKED_PACK_LOCK_INVALID,
    BLOCKED_PACK_LOCK_MISMATCH,
    BLOCKED_SURFACE_CONFLICT,
    BLOCKED_RULESET_HASH_MISMATCH,
    BLOCKED_ACTIVATION_HASH_MISMATCH,
    BLOCKED_RELEASE_HYGIENE,
    BLOCKED_SESSION_STATE_LEGACY_UNSUPPORTED,
    BLOCKED_UNSPECIFIED,
    BLOCKED_PERSISTENCE_TARGET_DEGENERATE,
    BLOCKED_PERSISTENCE_PATH_VIOLATION,
    BLOCKED_PERMISSION_DENIED,
    BLOCKED_EXEC_DISALLOWED,
    BLOCKED_FINGERPRINT_MISMATCH,
    BLOCKED_INTEGRITY_FAILED,
    BLOCKED_REPO_ROOT_NOT_DETECTABLE,
    BLOCKED_LEGACY_DECISION_PACK_FORMAT,
    BLOCKED_INVALID_NEXT_ACTION,
    BLOCKED_GOLDEN_BASELINE_MODIFIED_IN_PR,
    BLOCKED_REPO_DISCOVERY,
    BLOCKED_RECOVERY_REQUIRED,
    BLOCKED_P5_3_TEST_QUALITY_GATE,
    BLOCKED_P5_4_BUSINESS_RULES_GATE,
    BLOCKED_P5_5_TECHNICAL_DEBT_GATE,
    BLOCKED_P5_6_ROLLBACK_SAFETY_GATE,
    BLOCKED_P4_INTAKE_MISSING_EVIDENCE,
    BLOCKED_P5_PLAN_RECORD_PERSIST,
    BLOCKED_P5_PHASE_MISMATCH,
    BLOCKED_P5_TICKET_EVIDENCE_MISSING,
    BLOCKED_P5_PLAN_EMPTY,
    BLOCKED_P5_REVIEW_PERSIST_FAILED,
    BLOCKED_P6_PREREQUISITES_NOT_MET,
    BLOCKED_P6_PLAN_COMPLIANCE_MAJOR,
    BLOCKED_REVIEW_DECISION_INVALID,
    # Pipeline hard-blocks
    BLOCKED_PIPELINE_INTERACTIVE,
    BLOCKED_PIPELINE_HUMAN_ASSIST,
    BLOCKED_PIPELINE_PROMPT_BUDGET,
    BLOCKED_RECEIPT_MISSING_TYPE,
    BLOCKED_RECEIPT_MISSING_GATE,
    BLOCKED_RECEIPT_MISSING_DIGEST,
    BLOCKED_RECEIPT_MISSING_SESSION,
    BLOCKED_RECEIPT_MISSING_STATE_REVISION,
    BLOCKED_RECEIPT_MISSING_SCOPE,
    BLOCKED_RECEIPT_MISSING_TIMESTAMP,
    BLOCKED_RECEIPT_TYPE_MISMATCH,
    BLOCKED_RECEIPT_GATE_MISMATCH,
    BLOCKED_RECEIPT_DIGEST_MISMATCH,
    BLOCKED_RECEIPT_SESSION_MISMATCH,
    BLOCKED_RECEIPT_STATE_REVISION_MISMATCH,
    BLOCKED_RECEIPT_SCOPE_MISMATCH,
    BLOCKED_RECEIPT_INVALID_TIMESTAMP,
    BLOCKED_RECEIPT_STALE_TIMESTAMP,
    # Model identity
    BLOCKED_MODEL_IDENTITY_UNTRUSTED,
    BLOCKED_MODEL_CONTEXT_LIMIT_REQUIRED,
    BLOCKED_MODEL_CONTEXT_LIMIT_UNKNOWN,
    BLOCKED_MODEL_CONTEXT_LIMIT_INVALID,
    BLOCKED_MODEL_METADATA_FETCH_FAILED,
    BLOCKED_MODEL_IDENTITY_SOURCE_INVALID,
    # Install subsystem
    BLOCKED_INSTALL_PRECHECK_MISSING_SOURCE,
    BLOCKED_INSTALL_VERSION_MISSING,
    BLOCKED_INSTALL_CONFIG_ROOT_INVALID,
    # Contract drift
    BLOCKED_CONTRACT_LAYOUT_DRIFT,
    BLOCKED_CONTRACT_RUNTIME_DRIFT,
    BLOCKED_CONTRACT_OPENCODE_DRIFT,
    # Profile/addon BLOCKED
    BLOCKED_MISSING_DB_VERSION,
    BLOCKED_FORMAT_UNDEFINED,
    BLOCKED_MIGRATION_UNSAFE,
    BLOCKED_MIGRATION_NO_ROLLBACK,
    BLOCKED_MIGRATION_COMPATIBILITY,
    # WARN — kernel
    WARN_UNMAPPED_AUDIT_REASON,
    WARN_WORKSPACE_PERSISTENCE,
    WARN_ENGINE_LIVE_DENIED,
    WARN_MODE_DOWNGRADED,
    WARN_PERMISSION_LIMITED,
    WARN_SESSION_STATE_LEGACY_COMPAT_MODE,
    WARN_P6_STATE_INCONSISTENCY,
    # WARN — profile/addon
    WARN_DOCS_README_DRIFT,
    WARN_DOCS_SCHEMA_DRIFT,
    WARN_DOCS_MANIFEST_RULEBOOK_MISSING,
    WARN_FALLBACK_BASELINE_UNKNOWN,
    WARN_FALLBACK_TESTING_INSUFFICIENT,
    WARN_FALLBACK_RECOVERY_UNSPECIFIED,
    WARN_PRINCIPAL_EVIDENCE_MISSING,
    WARN_SCORECARD_CALIBRATION_INCOMPLETE,
    WARN_RISK_TIER_UNRESOLVED,
    WARN_OPENAPI_SPEC_IMPLEMENTATION_MISMATCH,
    WARN_OPENAPI_VERSION_UNKNOWN,
    WARN_OPENAPI_MISSING_SPEC,
    WARN_OPENAPI_BREAKING_CHANGE_UNAPPROVED,
    WARN_FE_OPENAPI_GENERATOR_UNKNOWN,
    WARN_FE_OPENAPI_DRIFT_RISK,
    WARN_FE_OPENAPI_NO_NEGATIVE_TEST,
    WARN_FE_OPENAPI_SOURCE_UNRESOLVED,
    WARN_FE_OPENAPI_MAPPING_DRIFT_RISK,
    WARN_FE_OPENAPI_CONTRACT_TEST_MISSING,
    WARN_KAFKA_IDEMPOTENCY_UNVERIFIED,
    WARN_KAFKA_RETRY_POLICY_UNKNOWN,
    WARN_KAFKA_ASYNC_FLAKINESS_RISK,
    WARN_CYPRESS_FLAKY_RISK,
    WARN_CYPRESS_SELECTOR_UNSTABLE,
    WARN_CYPRESS_NO_CRITICAL_FLOW_COVERAGE,
    WARN_CYPRESS_NETWORK_CONTROL_MISSING,
    WARN_CYPRESS_CRITICAL_PATH_MISSING,
    WARN_CYPRESS_ASYNC_FLAKE_RISK,
    WARN_CUCUMBER_VERSION_UNKNOWN,
    WARN_CUCUMBER_RUNNER_UNKNOWN,
    WARN_CUCUMBER_CONVENTIONS_UNKNOWN,
    WARN_CUCUMBER_FLAKINESS_RISK,
    WARN_CUCUMBER_NO_EVIDENCE,
    WARN_JAVA_DETERMINISM_RISK,
    WARN_BUILD_TOOL_MISSING,
    WARN_ANGULAR_BOUNDARY_DRIFT,
    WARN_ANGULAR_STATE_PATTERN_MIX,
    WARN_ANGULAR_ASYNC_DETERMINISM,
    WARN_PYTHON_MIGRATION_ROLLBACK_MISSING,
    WARN_PYTHON_ASYNC_DETERMINISM,
    WARN_PYTHON_TYPE_CHECK_SKIPPED,
    WARN_LIQUIBASE_PG_VERSION_UNKNOWN,
    WARN_LIQUIBASE_ROLLBACK_MISSING,
    WARN_LIQUIBASE_LOCK_RISK,
    WARN_LIQUIBASE_DATA_MIGRATION_UNVERIFIED,
    WARN_SESSION_STATE_SCHEMA_VIOLATION,
    WARN_P6_PLAN_COMPLIANCE_DRIFT,
    # NOT_VERIFIED
    NOT_VERIFIED_MISSING_EVIDENCE,
    NOT_VERIFIED_EVIDENCE_STALE,
    # Strict-exit enforcement (principal_strict mode)
    BLOCKED_STRICT_EVIDENCE_MISSING,
    BLOCKED_STRICT_EVIDENCE_STALE,
    BLOCKED_STRICT_THRESHOLD,
    BLOCKED_STRICT_CONTRACT_MISSING,
    NOT_VERIFIED_STRICT_EVIDENCE_STALE,
    NOT_VERIFIED_STRICT_EVIDENCE_MISSING,
    # Operational
    REPO_DOC_UNSAFE_DIRECTIVE,
    REPO_CONSTRAINT_WIDENING,
    REPO_CONSTRAINT_UNSUPPORTED,
    INTERACTIVE_REQUIRED_IN_PIPELINE,
    PROMPT_BUDGET_EXCEEDED,
    POLICY_PRECEDENCE_APPLIED,
    # Persistence gate
    PERSIST_CONFIRMATION_REQUIRED,
    PERSIST_CONFIRMATION_INVALID,
    PERSIST_DISALLOWED_IN_PIPELINE,
    PERSIST_PHASE_MISMATCH,
    PERSIST_GATE_NOT_APPROVED,
)


def is_registered_reason_code(reason_code: str, *, allow_none: bool = True) -> bool:
    """Check exact membership in the canonical registry."""
    normalized = reason_code.strip()
    if allow_none and normalized == REASON_CODE_NONE:
        return True
    return normalized in CANONICAL_REASON_CODES


def is_registered_reason_code_or_parameterized(
    reason_code: str, *, allow_none: bool = True
) -> bool:
    """Check membership including parameterized codes (e.g. ``BLOCKED-MISSING-ADDON:<key>``)."""
    if is_registered_reason_code(reason_code, allow_none=allow_none):
        return True
    normalized = reason_code.strip()
    return any(normalized.startswith(prefix) for prefix in _PARAMETERIZED_PREFIXES)


REASON_CODE_HINTS: Final[dict[str, str]] = {
    BLOCKED_INSTALL_PRECHECK_MISSING_SOURCE: (
        "Required governance source files are missing. "
        "If installing from source: clone the repository. "
        "If using a bundle: extract it first, then run install.py from the extracted directory. "
        "If already installed: run '${PYTHON_COMMAND} install.py --status' to check installation health."
    ),
    BLOCKED_INSTALL_VERSION_MISSING: (
        "Governance version metadata not found. "
        "Ensure governance/VERSION contains a semantic version."
    ),
    BLOCKED_INSTALL_CONFIG_ROOT_INVALID: (
        "Config root path is invalid or not writable. "
        "Check path permissions and try again."
    ),
}
