"""Legacy compatibility bridge for write policy.

DEPRECATED: use governance_runtime.infrastructure.write_policy.
"""

from governance_runtime.infrastructure.write_policy import (
    BLOCKED_PERSISTENCE_PATH_VIOLATION,
    BLOCKED_PERSISTENCE_TARGET_DEGENERATE,
    DETAIL_KEY_DRIVE_LETTER_ONLY,
    DETAIL_KEY_DRIVE_RELATIVE,
    DETAIL_KEY_DRIVE_ROOT_ONLY,
    DETAIL_KEY_EMPTY_TARGET,
    DETAIL_KEY_INVALID_VARIABLE_TOKEN,
    DETAIL_KEY_NON_VARIABLE_PATH,
    DETAIL_KEY_PARENT_TRAVERSAL,
    DETAIL_KEY_SINGLE_SEGMENT_RELATIVE,
    DETAIL_KEY_UNKNOWN_VARIABLE,
    DETAIL_OK,
    _ALLOWED_CANONICAL_VARIABLES,
    WriteTargetPolicyResult,
    evaluate_target_path,
)

__all__ = [
    "DETAIL_KEY_DRIVE_LETTER_ONLY",
    "DETAIL_KEY_DRIVE_RELATIVE",
    "DETAIL_KEY_DRIVE_ROOT_ONLY",
    "DETAIL_KEY_EMPTY_TARGET",
    "DETAIL_KEY_INVALID_VARIABLE_TOKEN",
    "DETAIL_KEY_NON_VARIABLE_PATH",
    "DETAIL_KEY_PARENT_TRAVERSAL",
    "DETAIL_KEY_SINGLE_SEGMENT_RELATIVE",
    "DETAIL_KEY_UNKNOWN_VARIABLE",
    "DETAIL_OK",
    "BLOCKED_PERSISTENCE_PATH_VIOLATION",
    "BLOCKED_PERSISTENCE_TARGET_DEGENERATE",
    "_ALLOWED_CANONICAL_VARIABLES",
    "WriteTargetPolicyResult",
    "evaluate_target_path",
]
